### ISSUE TITLE
"No items" with "Safely use the Internet"

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#104]
When deleting a/the? "Secure Internet" provider and then trying to add it again results in a "No items" on the page where you would normally see the country flags.

![image](https://user-images.githubusercontent.com/616885/49158021-7e1b7880-f321-11e8-9e5c-4de5b772d798.png)

**Comment by rozmansi** [comment]
I confirm this bug is repeatable. Will look into it...
