### ISSUE TITLE
OpenVPN GUI deinstall removes eduVPN tap-driver

### ISSUE THREAD

**Issue by efef** [Amebis/eduVPN#105]
WiX believes, the TAP driver is installed, but OpenVPN GUI uninstalled it without WiX noticing it.
Result of the problem is that the interactive service isn't running and eduVPN client isn't working after deinstallation of OpenVPN GUI.

Also upgrading the eduVPN client to another release will give an error.

**Comment by rozmansi** [comment]
There is not much we can do about this. OpenVPN NSIS installer has no built-in check (or a reference counter) anybody else besides OpenVPN is using TAP driver. It always uninstalls it clean.

As for the interactive service, I am surprised to read that. The eduVPN and Let's Connect! clients both package their own interactive service binary. Those services have independent names and are installed in independent folders. Therefore, the OpenVPN uninstall should have no effect on their interactive service copies. Even eduVPN and Let's Connect! copies of the interactive service are different (different names, paths, GUIDs) and those clients should never ever uninstall each other's interactive service.

The TAP driver is a big problem thou. OpenVPN, eduVPN and Let's Connect! all share the one and only `tap0901.sys`. What's more - they don't have a check to see if anybody else is using it when they uninstall.

We cannot rename and fork the TAP driver that easily. We'd need to EV sign it then, HLK test it to have Microsoft certify it, keep it up-to-date with the upstream version...

The easiest approach would be to make a consent with OpenVPN we all stop uninstalling TAP driver. That would leave stale TAP adapters on client computers, which is far from optimal. Perhaps we should all start naming TAP adapters (or tag it some other way) and remove them on uninstall while leaving the driver installed.

**Comment by rozmansi** [comment]
With the switch to Wintun, this issue is now obsolete.

Actually it was fixed with the official OpenVPN 2.5.0 release switching to MSI installers that have TAP-Windows driver reference count.
