### ISSUE TITLE
client does not attempt to reconnect after being 'kicked' offline

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#107]
In Let's Connect! / eduVPN a client will be (eventually) disconnected after the client certificate expires. By default a cron runs every hour that looks for connected clients that use expired certificates and disconnects them.

The Windows app does not seem to recover from this, and just hangs. It can be tested with https://frkoidp.tuxed.net/ where a client certificate expires after 3 minutes, and the cron runs every 5 minutes to disconnect clients. I tested it with "force TCP" as that will indicate immediately in the client when it is kicked offline.

![image](https://user-images.githubusercontent.com/616885/55403345-f30ff080-5555-11e9-93da-1e0f96cf6425.png)

**Comment by fkooman** [comment]
Expected behavior: try to obtain a new certificate if the current OAuth access_token and/or refresh_token still works, otherwise start the authorization flow.

**Comment by rozmansi** [comment]
`frkoidp.tuxed.net` doesn't resolve.

**Comment by fkooman** [comment]
> `frkoidp.tuxed.net` doesn't resolve.

Sorry, I meant frkovpn.tuxed.net :-)
