### ISSUE TITLE
after TOTP request, nothing happens

### ISSUE THREAD

**Issue by efef** [Amebis/eduVPN#108]
An user complains, after entering TOTP code nothing happens. eduVPN icon is still yellow.
A re-install of eduVPN client and even new enrollment TOTP didn't solve the issue.
the OpenVPN log shows:
--
Thu Apr 04 14:10:30 2019 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018
Thu Apr 04 14:10:30 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Thu Apr 04 14:10:30 2019 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10
Enter Management Password:
Thu Apr 04 14:10:30 2019 MANAGEMENT: Connected to management server at [AF_INET]127.0.0.1:51313
Thu Apr 04 14:10:30 2019 MANAGEMENT: CMD 'state on all'
Thu Apr 04 14:10:30 2019 MANAGEMENT: CMD 'echo on all'
Thu Apr 04 14:10:30 2019 MANAGEMENT: CMD 'bytecount 5'
Thu Apr 04 14:10:30 2019 MANAGEMENT: CMD 'hold release'
Thu Apr 04 14:10:35 2019 MANAGEMENT: CMD 'username Auth totp'
Thu Apr 04 14:10:35 2019 MANAGEMENT: CMD 'username Auth totp'

--
The Event log shows two events related to OpenVPN

Error:
"The description for Event ID 0 from source openvpnserv cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

by detail: 
openvpnserv$eduVPN error: 

0x20000000 OpenVPN exited with error: exit code = 1

--
before the error in the event log I notice an informational openvpn event: 

The description for Event ID 0 from source openvpnserv cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

openvpnserv$eduVPN: 
Authorizing user 'Marcel@DELL-LAPTOP' by virtue of membership in group 'Administrators'

The request is not supported

**Comment by fkooman** [comment]
This issue won't be triggered in Let's Connect! / eduVPN 2.0 as there is no 2FA anymore on the VPN connection itself. Maybe not worth fixing?
