### ISSUE TITLE
"Add Other Provider" is missing in Windows Client

### ISSUE THREAD

**Issue by ThomasKaule** [Amebis/eduVPN#109]
For Android and IOS you can select "Safely use the Internet", "Connect to your Instituts's Network" AND "Add Other Provider".  The last choice is missing on the Windows Client

**Comment by fkooman** [comment]
We decided at some point to remove that from the eduVPN branded application but didn't get around to do that on the other platforms. We may have to reconsider this though...

However, you can use the "Let's Connect!" branded app to connect to your own server if it is not yet in the eduVPN app: https://app.letsconnect-vpn.org/

**Comment by gvde** [comment]
I'd rather see it included in the eduVPN client as you can have everything in one place then instead of using two different apps depending on your target for doing essentially the same...

**Comment by fkooman** [comment]
I guess that's a fair point. Also, it is very easy to add the "other server" button back...

**Comment by rozmansi** [comment]
Granted. And this is good timing too... Just about to publish a new release this week.

**Comment by ThomasKaule** [comment]
You built a new version 1.0.27 which works fine but still isn't official released.

Choosing  windows in https://www.eduvpn.org/apps.html downloads eduVPNClient_latest which is the old 1.0.26 version.

And https://app.eduvpn.org/ lists all version with the possibility to down load a specific one - but again 1.0.26 is last one in the list.

So when will the official release happen ?

**Comment by fkooman** [comment]
Waiting for @efef to approve releasing.

**Comment by fkooman** [comment]
> Waiting for @efef to approve releasing.

Apparently was already approved, but I missed that. Will release tonight!

**Comment by fkooman** [comment]
Okay. released!
