### ISSUE TITLE
eduVPN bricks user after IdP switch

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#116]
First of all, this issue is currently highly situational, but since this situation will probably occur much more often starting in 2020 it's good to think about it. Secondly: this is actually not just one but multiple issues (probably with the same cause, but not sure). And thirdly: I'm not sure whether this behavior is due to the Windows specific implementation or due to eduVPN in general. But @fkooman and @rozmansi can probably find this out ;-).

## Situation
SURFnet employee now works for SURF (another organization with its own IdP). He is deprovisioned on the SURFnet IdP and is provisioned on the SURF IdP. eduVPN can't handle this gracefully, now the following happens:

1) The user gets a notice that re-authentication is required (this is good, although I'm not sure whether this is due to the default expiry of some access token or due to the swap in IdP. I would guess the default expiry since we don't check IdP credentials on every use of the app, but instead use our own certificates).
2) eduVPN sents the user to the browser, specifically to the SURFnet IdP. Of course this fails, since the user cannot login on the SURFnet IdP anymore. There does not seem to be an option to login on another IdP.
3) When closing the 'Waiting for authentication' screen (since the user cannot login to the IdP enforced by eduVPN) on eduVPN, the user is perfectly able to connect to eduVPN, and the eduVPN status icon even is green. But: traffic is not possible! So it looks like it works, but doesn't actually work.

## Issues
The two issues as far as I can tell:
1) The application doesn't let you switch to another IdP in these circumstances.
2) The application lets you connect (and gives a green status) wrongfully: the app says that everything is connected and okay, but there is no internet connection possible. When not authenticated you shouldn't be able to connect, let alone get a green status.

My guess would be that the user needs to authenticate again on one of the profile types (where multiple IdP's can be chosen), but it seems that all options are bricked. Even after clicking 'add another', this user isn't able to choose his SURF IdP and it still seems to be locked on the SURFnet IdP. Which is weird since the SURF IdP is listed on the nl.eduvpn.org portal.

I don't know what the best solution might be, but in the near future this problem will exist for hundreds of people since some major IdP swaps are upcoming in 2020. 

*edit*
It hangs on this screen:
![image](https://user-images.githubusercontent.com/12334213/64426369-e6ac3880-d09d-11e9-9181-c1d6da695ce9.png)
And since you can't select your new IdP, you are bricked.

**Comment by fkooman** [comment]
This is expected behavior. Nothing there reads as a bug. The user probably has both nl.eduvpn.org and surfnet.eduvpn.nl configured in the app. The first will stay working, the second one won't after the current token/certificate expires. So it seems you are mixing those two up :) Just delete the surfnet.eduvpn.nl entry from the app and you are good to go. Once the nl.eduvpn.org expires (after 90 days) the user will see the WAYF of nl.eduvpn.org and can then choose SURF instead of SURFnet.

**Comment by sveeke** [comment]
Maybe. But:

1) This use can't select his IdP from the list.
2) How can you 'just delete the surfnet.eduvpn.nl' entry? I tried it in my own app, but can't find this option. On Android it's possible by swiping the profile name to the border of the app, but that isn't possible on the Windows app.
3) I think the expiry after 90 days already occured, but the user can't select his IdP.

And also: the app giving a green status without making a full VPN connection would qualify as a bug. That can't be intended since it's misleading, especially within the context of a VPN service focused on privacy and security ;-).

**Comment by fkooman** [comment]
> This use can't select his IdP from the list.

The surfnet.eduvpn.nl entry does NOT have a WAYF, so there is nothing to select.

> How can you 'just delete the surfnet.eduvpn.nl' entry? I tried it in my own app, but can't find this option. On Android it's possible by swiping the profile name to the border of the app, but that isn't possible on the Windows app.

Right click on it and choose delete/remove.

> I think the expiry after 90 days already occured, but the user can't select his IdP.

Not for nl.eduvpn.org, because if that would be the case you'd see the WAYF with all IdPs that have access to nl.eduvpn.org

**Comment by sveeke** [comment]
It works now! In the end there were three problems:

1) The user couldn't find a way to remove the profile (not very clear in the gui).
2) The gui let the user connect (with green status) but an internet connection was not possible.
3) SURF doesn't have a Institute Access eduVPN instance, so the user was falsely under the impression that his institution should be included in the list with instances.

Maybe we could make 1 more pronounced in the GUI? And I asked for logs about 2 so we might be able to find how this is possible.

**Comment by rozmansi** [comment]
1. IIRC the profile should automatically disappear from the list once its token is no longer refreshed. But, I should double-check this. Maybe the Windows client just considers this a temporary condition.
2. That should indeed not happen. I will need some assistance to reproduce this condition to be able to fix it.

**Comment by rozmansi** [comment]
This issue has been inactive for two years.
