### ISSUE TITLE
Feature request: configurable local routing

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#117]
As of now, eduVPN (as a service) has two flavors regarding local routing:

1. We enable local routing for all: all clients can reach their local network (NAS, SAN, servers, other devices etc.) but are less protected against man-in-the-middle. In most home situations, the MITM risk is quite small (and if true, then you have much bigger problems). But this risk is far greater on public hotspots, and this risk is even one of the primary reasons for the existence of eduVPN. Hence 2:

2. We disable local routing for all: all clients can't reach their local network and eduVPN offers better protection against MITM.

At the SURFnet office we have two profiles in use: employees profile (with enabled local routing) and the nl.eduvpn.org profile (which disabled local routing) and I noticed that quite a few people make the choice based on the local routing capabilities. Unfortunately, you really must use the empoyees profile simply because that allows access to a lot of stuff. There were even people that made the effort of complaining to our office automation department that 'eduVPN was unusable because they can't use their NAS/shares at home".

Some users now don't use the eduVPN app because of this, they download a config file and run it in their ovpn client where they allow the local routing themselves. This might work now (although very user unfriendly), since the certs are valid for 1 month, but when we are going to use short-lived certs this will be impossible to ask of users.

Well long story short, this feature matters and looking broader than this specific scenario I think it's a good idea to include a configurable parameter or something to the eduVPN apps that allows users to opt-in for local routing. Opt-in because the sane default would be to disable local routing, since it's a privacy focused VPN service.

@fkooman @rozmansi how do you think and feel about this feature and possible change? My gut feeling is that it shouldn't be too hard to make this configurable in the client, since the client allows or disallows this behavior (more or less like 'force tcp/443').

**Comment by rozmansi** [comment]
I don't see any drawbacks not to implement this in the Windows client. Technically, this is very similar to the "Use TCP" setting - just a checkbox that affects injecting (or removing) a setting from .ovpn profile.

Please, have @efef, @fkooman and you decide if this is OK, and I can add it.

**Comment by rozmansi** [comment]
There are `OpenVPNRemoveOptions` and `OpenVPNAddOptions` XML settings user could add to their local app.config. But a GUI options to manipulate this would indeed be preferable.

**Comment by fkooman** [comment]
`block-local` is an option that's pushed from the server... so it would have to be filtered from the list of received options.

**Comment by rozmansi** [comment]
![image](https://user-images.githubusercontent.com/6889694/68304531-38753d00-00a6-11ea-9ae9-360b0e5bb4ce.png)

This is doable. I have saved it in a separate branch until there is a wide consensus we _want_ this in eduVPN/Let's Connect! clients.
