### ISSUE TITLE
Question/possible bug: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#118]
On the most recent version of the eduVPN for Windows client, a user got this error while trying to connect to Norway's instance:
```
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at eduVPN.ViewModels.VPN.OpenVPNSession.DoRun()
   at eduVPN.ViewModels.VPN.VPNSession.Run()
   at eduVPN.ViewModels.Windows.ConnectWizard.<>c__DisplayClass24_0.<get_StartSession>b__2()
```
After a couple of minutes the user was able to use the VPN instance again. What can generate this error? Is it a bug or error on the side of the VPN administrator? We couldn't figure it out, so ask it here :-).

**Comment by rozmansi** [comment]
[`eduVPN.ViewModels.VPN.OpenVPNSession.DoRun()`](https://github.com/Amebis/eduVPN/blob/master/eduVPN/ViewModels/VPN/OpenVPNSession.cs#L144) is huge, but I suspect the eduVPN <-> OpenVPN Interactive Service communication got interrupted. Probably the OpenVPN$eduVPN Interactive Service died for some reason.

Should this be repeatable, I would definitely like to research the reason why this happens.

**Comment by sveeke** [comment]
Okay. I'll notify the user that when it happens again he pings us. Cheers!
