### ISSUE TITLE
Problem loading DLL 

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#119]
![image1](https://user-images.githubusercontent.com/616885/66379792-76ebdf00-e9b6-11e9-9fa6-0f3667efe201.jpeg)

I asked them to reinstall eduVPN, but apparently that didn't help...

**Comment by rozmansi** [comment]
This means "eduEd25519.dll file not found", right?

**Comment by fkooman** [comment]
> This means "eduEd25519.dll file not found", right?

That's what I thought...

**Comment by TanguiC** [comment]
it means this file or one of his dependencies could not be read. The named module was not found

**Comment by fkooman** [comment]
I tried deleting this DLL file in my Windows installation of eduVPN. When I started eduVPN it just restored the DLL file... Self healing, that's funny!

**Comment by fkooman** [comment]
We recommended now:

1. Uninstall "eduVPN Client", "eduVPN Client Core", "TAP-Windows"
2. Reboot
3. Install eduVPN again from https://app.eduvpn.org/ (latest version!)
4. Try again to use eduVPN app

**Comment by TanguiC** [comment]
The user says they get the same error after following this procedure

**Comment by rozmansi** [comment]
> I tried deleting this DLL file in my Windows installation of eduVPN. When I started eduVPN it just restored the DLL file... Self healing, that's funny!

It's called _advertised shortcuts_ in Windows. It's a special kind of shortcut that doesn't directly point to an EXE file. Instead, it points to Microsoft Installer with specified product GUID and feature ID that this shortcut represents. Microsoft Installer checks that the feature has all its components installed before invoking the EXE file. This provides self-healing and/or on-demand features functionality.

**Comment by rozmansi** [comment]
> The user says they get the same error after following this procedure

A possible reason why eduEd25519.dll is not loaded can also be that the computer is missing one of eduEd25519.dll's dependencies.

It directly depends on VCRUNTIME140.dll, api-ms-win-crt-runtime-l1-1-0.dll, api-ms-win-crt-heap-l1-1-0.dll, and mscoree.dll. Those are a part of Visual C++ Runtime Libraries. The installer should take care of their installation into C:\WINDOWS\system32. As the folder name implies, those are shared DLLs. Maybe some other application's reference counting is broken and uninstalled any or all of them by accident.

If that's the case, they can be reinstalled: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I have double-checked the eduVPN setup and it installs them fine (on a vanilla Windows 10 x64 and vanilla Windows 7 x86).

**Comment by fkooman** [comment]
I asked them to install the VC runtime exe again:

> It should be possible to fix this yourself by going to the following
> Microsoft site:
>
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
>
> Then download the "x64: vc_redist.x64.exe" file and install it.
>
> After a reboot, eduVPN should work.
>
> If it doesn't, we'll continue looking!

Good luck!

**Comment by rozmansi** [comment]
I believe I found the reason for this issue...

I forgot to bump the version of some DLLs. MSI assumed DLL unchanged on update and didn't replace them. Binary incompatibility led to DLLs load failure. This applies to updated setups only. Fresh installations are unaffected.
