### ISSUE TITLE
unclear error message

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#120]
![image](https://user-images.githubusercontent.com/616885/66545982-2ef6c480-eb3c-11e9-874f-dbd7e82badde.png)

![image](https://user-images.githubusercontent.com/616885/66546050-5b124580-eb3c-11e9-9730-eb4cf4a47588.png)

(sorry copy/paste does not work from my VM)

**Comment by efef** [comment]
Looks like this issue will also be triggered when the user session expires.

**Comment by fkooman** [comment]
> user session

the OAuth `access_token` I guess. Or maybe also/only `refresh_token`?
