### ISSUE TITLE
add other provider with space

### ISSUE THREAD

**Issue by gvde** [Amebis/eduVPN#122]
When you accidentally enter a space into the URL field when adding another provider you'll get an API access error, e.g. enter a space after the url like this: "https://eduvpn.example.org/ ". The text field should be clear of white space in front and at the end before proceeding...

**Comment by rozmansi** [comment]
You should get something like this:
![image](https://user-images.githubusercontent.com/6889694/69147646-cacc0680-0ad2-11ea-9feb-5b02e297ff33.png)

The "Connect" button will get disabled and the warning sign will say "Invalid hostname: hostnames contain letters, numbers, hyphens and dots." on hover.

Nevertheless, building in some whitespace trimming around the hostname is a problem at all:
![image](https://user-images.githubusercontent.com/6889694/69148383-76298b00-0ad4-11ea-9a77-7b52494ce700.png)
