### ISSUE TITLE
Windows 10 no resume after sleep

### ISSUE THREAD

**Issue by efef** [Amebis/eduVPN#124]
It seems the client isn't autoconnecting after Windows 10 sleep. User needs to manually disconnect/connect.
![image](https://user-images.githubusercontent.com/3393474/68757178-c6ec4000-060b-11ea-8087-d8f76505252d.png)

**Comment by rozmansi** [comment]
IIRC, @lstipakov changed resume-form-sleep behaviour in the latest version of TAP-Windows6 driver, so complete OpenVPN stack handles sleep much better.

My testing confirms resume from sleep works now (within eduVPN client):

```
--- snip ---
Tue May 19 13:56:06 2020 IPv6 route addition via service succeeded
Tue May 19 13:56:06 2020 Initialization Sequence Completed
Tue May 19 13:56:06 2020 MANAGEMENT: >STATE:1589889366,CONNECTED,SUCCESS,145.90.227.76,145.100.179.16,1195,,,2001:610:450:30::2:100a
--- sleep ---
Tue May 19 14:01:10 2020 [20200420105936.internet] Inactivity timeout (--ping-restart), restarting
Tue May 19 14:01:10 2020 C:\WINDOWS\system32\route.exe DELETE 145.100.179.16 MASK 255.255.255.255 10.91.100.1
Tue May 19 14:01:10 2020 Warning: route gateway is not reachable on any active network adapters: 10.91.100.1
Tue May 19 14:01:10 2020 Route deletion via service failed
Tue May 19 14:01:10 2020 C:\WINDOWS\system32\route.exe DELETE 0.0.0.0 MASK 128.0.0.0 145.90.227.65
Tue May 19 14:01:10 2020 Route deletion via service succeeded
Tue May 19 14:01:10 2020 C:\WINDOWS\system32\route.exe DELETE 128.0.0.0 MASK 128.0.0.0 145.90.227.65
Tue May 19 14:01:10 2020 Route deletion via service succeeded
--- snip ---
Tue May 19 14:01:43 2020 add_route_ipv6(3000::/4 -> 2001:610:450:30::3:1 metric -1) dev eduVPN
Tue May 19 14:01:43 2020 IPv6 route addition via service succeeded
Tue May 19 14:01:43 2020 add_route_ipv6(fc00::/7 -> 2001:610:450:30::3:1 metric -1) dev eduVPN
Tue May 19 14:01:43 2020 IPv6 route addition via service succeeded
Tue May 19 14:01:43 2020 Initialization Sequence Completed
Tue May 19 14:01:43 2020 MANAGEMENT: >STATE:1589889703,CONNECTED,SUCCESS,145.90.227.104,145.100.179.16,1195,10.91.100.109,54663,2001:610:450:30::3:1006
```

However, OpenVPN does a full cleanup and reconnect, which seems kind of excessive. But probably required if you switch your network adapter (wired - wireless) when the computer is asleep or hibernating.

Nevertheless, eduVPN client being a software application is not disturbed by sleep. Unless interrupted when retrieving discovery data from the web - which is a very short window and difficult to hit. All other sleep implications are OpenVPN related. So, should OpenVPN have any issues with Windows resuming from sleep, we'd need to fix OpenVPN first.
