### ISSUE TITLE
some more 2fa artefacts are left

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#127]
When code searching for "two_factor" I find some more stuff that is left over. E.g. the `/profile_list` call. See https://github.com/eduvpn/documentation/blob/v2/API.md#profile-list

https://github.com/Amebis/eduVPN/blob/36e89312af9ae9c3c134c408bcc990c964712356/eduVPN/Models/Profile.cs#L74

**Comment by rozmansi** [comment]
I understood that 2FA enrollment was to be removed only. So, users having existing 2FA enrollment can still authenticate using TOTP and YubiKey.

2FA should be removed completely now, right?

**Comment by fkooman** [comment]
> I understood that 2FA enrollment was to be removed only. So, users having existing 2FA enrollment can still authenticate using TOTP and YubiKey.
> 
> 2FA should be removed completely now, right?

There *may* be still some eduVPN 1.x servers out there that still support 2FA, but the app can remove all 2FA stuff, including asking for 2FA on connect.

**Comment by rozmansi** [comment]
1,126 lines of code removed. 👍 
All that work discarded. 👎 

The bottom line: less bloat to maintain, the lighter we carry on...
