### ISSUE TITLE
Authorized windows application revoked ends up in unclear error

### ISSUE THREAD

**Issue by mkoelewijn** [Amebis/eduVPN#129]
When you revoke the Authorized Application the client will show the following error. Only way to get connected again is to remove the instance and add it again.

![image](https://user-images.githubusercontent.com/26085443/73694581-a0a0e280-46d8-11ea-98e8-e4ccef0824c5.png)

**Comment by fkooman** [comment]
Reproduced on vpn.tuxed.net:

```
STATUS: 401
HEADERS:
Content-Type:application/json
WWW-Authenticate:Bearer realm="OAuth",error="invalid_token"
BODY: {"error":"invalid_token","error_description":"authorization for client \"org.eduvpn.app.windows\" no longer exists"}
```

**Comment by fkooman** [comment]
I am not sure why this doesn't trigger the (re)authorization by the app? Looks correct to me...

Similar: #120

**Comment by fkooman** [comment]
Could it be a JSON decoder issue with the escape double quotes?

**Comment by fkooman** [comment]
https://github.com/nst/JSONTestSuite :-)

**Comment by rozmansi** [comment]
Fixed it. In the end, it was not JSON. The cause was the code that tried to load 401 response body (for diagnostic), but the response had no charset defined and the loading exploded.
