### ISSUE TITLE
"switch user" should disconnect VPN

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#132]
When user X is connected to VPN and some other user arrives by "Switch User" the current VPN connection should be terminated.

**Comment by rozmansi** [comment]
Note to self: wtsapi32.h

**Comment by fkooman** [comment]
We got a report where when this (multiple users on the same system, logged in simultaneously, both using/connected using eduVPN) the clients go in a connect/disconnect loop and generate excessive amounts of (connect/disconnect) logging on the server.

**Comment by rozmansi** [comment]
I found a retry-loop where two WireGuard tunnels to the same server attempt to connect, cancelling each other out. Could add a ratelimiter, but by resolving this feature request, the retry-loop issue should be resolved too.
