### ISSUE TITLE
Notify user ~15 mins before certificate expiry they have to re-authorize soon

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#134]
This is to avoid that users unexpectedly need to re-authorize / reconnect at an inconvenient moment. I guess there should be an option to trigger 're-authorization' immediately from that point on or "ignore" it after which the client will re-authorize at the expiry time.

Maybe this 15 minutes can be made configurable for "MSI deployments".

**Comment by efef** [comment]
I notice when I put a windows VM in suspend first and meanwhile the certificate expires, after resuming the VPN client is still "green" for a minute, next it will turn yellow. Would be handy when resuming windows an user gets a notify that the certificate expired. Is it possible to detect a "resume" and notify if expired?
