### ISSUE TITLE
Update signatures

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#138]
At the moment we are using my libsodium based signer to generate signatures for Windows eduVPN/Let's Connect! app updates. Is this *really* necessary? The application itself is already signed as well, right?

In any case, it would be neat if in the future we can use standard tooling, like [minisign](https://jedisct1.github.io/minisign/), to generate signatures if we have to keep doing this.

Thoughts? Are there more "native" Windows ways of doing this?

**Comment by rozmansi** [comment]
The self-update code downloads a discovery JSON file first, which needs to be signed. It is here, that we establish trust now.

We could switch to an unsigned JSON discovery file and drop the SHA thumbprint matching.

Assuming HTTPS is secure to MitM attacks, we don't even need to check the Authenticode signature of the downloaded binary, as long as the JSON discovery file and the binary are both retrieved using secure HTTPS, right?

One thing we must upgrade or drop then is caching the downloaded binary. With SHA thumbprints in JSON discovery file gone, we cannot verify the integrity of the cached binary before launch. Relying on a valid Authenticode signature only would open the door too wide.

I would like to avoid code-signing certificate pinning. The certificate rollover needs to be performed very carefully and performing it once every few years only makes it even riskier.

**Comment by fkooman** [comment]
Okay, so a signature over both the binary and the JSON file would be nice to keep? It would still be nice if we can simply move to `minisign -S file.json` and `minisign file.exe` and be done with it. It becomes much easier for others to sign the file(s) and doesn't require my specific tools,,,
