### ISSUE TITLE
Unable to connect to eduVPN service

### ISSUE THREAD

**Issue by jornane** [Amebis/eduVPN#140]
A user was suddenly not able to use eduVPN anymore and got this error. Rebooting did not resolve the problem.

The last line means "The operation was timed out"

![image](https://user-images.githubusercontent.com/767872/81537701-e3c0c080-936d-11ea-9104-ab644082ffbb.png)

This is a managed device, so eduVPN was installed through some deployment mechanism.

**Comment by rozmansi** [comment]
Can you check if the "OpenVPN Interactive Service (eduVPN)" is enabled and started on the user computer, please? It's a vital component and it really needs to be running for eduVPN to connect.

Also, check the Event Log if something is preventing the service to start.

Related to another issue, I have discovered recently: the OpenVPN Interactive Service has `exit(1)` calls all over the place. This means that it will panic and service will terminate abnormally on first thing that goes other than planned.

**Comment by rozmansi** [comment]
I believe, I have finally found a cause of this:
https://github.com/Amebis/openvpn/commit/a71e31d2f1221e927bd09f2295a4603776df362c

I couldn't reproduce the issue, but analysing the code of OpenVPN's interactive service and extra feedback from @efef found one case when the interactive service terminates prematurely, following to the error @jornane reported.

eduVPN 1.0.36 contains fixed OpenVPN.
