### ISSUE TITLE
auto update + authorization require pop-up overload

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#147]
When both an auto-update is available and the user needs to re-authorize at a VPN server there are a few too many pop-ups. The user may also be confused in what to do first...

**Comment by rozmansi** [comment]
UI was redesigned:
- No pop-ups any more. Authorization prompt as well as  the new update prompt are now stand-alone wizard pages.
- Authorization is no longer auto-triggered on client startup, as the home screen no longer displays connection profiles. (Getting the list of profiles to display triggers OAuth in the v1.)
- At client startup, only update page might show. "Might" == "if an update detected"

![image](https://user-images.githubusercontent.com/6889694/102686818-6eae4700-41ea-11eb-989d-a5ddba89c5f5.png)
![image](https://user-images.githubusercontent.com/6889694/102686834-884f8e80-41ea-11eb-8b4e-3afb7da64337.png)

In theory, user could trigger OAuth by clicking the server to connect. Then wait a loooong time for us to publish the update (client checks for update once every 24 hours ±10%). Once update is available, the update page would display over the authorization page. User can choose to download and install the update, or click the Back button to get back to the authorization page.

V2 no longer has popup windows. But it continues the concept of popup pages (Settings, About were popup pages in v1 already). The popup pages display over the current wizard page and have the same Back button to dismiss them.
