### ISSUE TITLE
secure internet removal doesn't clean up properly

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#148]
When you right click on the country flag drop down and choose "Forget" not everything is properly cleaned up. This becomes visible when you have access to multiple IdPs belonging to different countries.

1. Add Netherlands, log in with Dutch IdP
2. All works great, including switching countries
3. Forget
4. Add Denmark, login with Danish IdP
5. Connecting works fine (to Denmark)
5. Switch countries
6. App still things your Dutch server is your home and wants to authorize/authenticate again before switching to other country.

After this I managed to crash the client (stopped responding) in some situation. However, that part I was not able to reproduce (yet).

I'm not sure how relevant this (still) is for the new design.

**Comment by rozmansi** [comment]
@fkooman, once I deliver v2, please confirm the Forget feature works flawlessly now. Mind that you will have to right-click on the "Change server" button to get the popup menu with Forget. Country server is not representative for Secure Internet, "Secure Internet" title can't receive keyboard focus making it impossible to popup a menu using keyboard only.
