### ISSUE TITLE
"Allow local traffic" has no effect

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#154]
Testing with the latest version of the eduVPN client.

When the server sends `block-local` LAN traffic does not work anymore, i.e. I can't "ping" laptop 1 from laptop 2 on the same WiFi anymore. Without VPN active, ping works. So far this is expected.

However, when flipping the toggle in the app that is supposed to allow local traffic it doesn't work. It blocks the local traffic anyway.

**Comment by rozmansi** [comment]
This feature was introduced in #117 and is unclear whether it ever worked and how it got merged into master anyway. Therefore, it will be removed.

**Comment by fkooman** [comment]
It applied a filter to the wrong element, it was a parameter of `redirect-gateway` that needed filtering, so it never actually worked on any client version on any OS...
