### ISSUE TITLE
eduVPN doesn't exit when I press the exit button

### ISSUE THREAD

**Issue by matjojo** [Amebis/eduVPN#155]
What happened:
1. I pressed the exit button.
2. The eduVPN program minimized itself to the system tray.

What did I expect to happen:
1. I press the exit button.
2. The eduVPN program exits.

I looked around in the settings but saw nothing to indicate that I can change this behaviour.

**Comment by rozmansi** [comment]
This is by design - to prevent accidental VPN connection termination - and is not configurable.

When you want to close the eduVPN client, right-click on the system tray icon to get a pop-up menu. Select Exit in that menu.
