### ISSUE TITLE
Client always hangs after waking windows 10 from sleep.

### ISSUE THREAD

**Issue by vosdev** [Amebis/eduVPN#156]
Windows 10 20H2 build 19042.685
Let's Connect version 1.0.35

Every day I wake my desktop or laptop from sleep I have to force-exit the Let'sConnect client, then re-start it again to get a functional VPN client.

reproducible by running the latest windows 10, have a VPN connection open and then put your computer to sleep. Wake up the next morning and your client will be in a broken connection state. Disconnect button does not work either.

**Comment by mmakaay** [comment]
I can confirm this behavior (as can many of my colleagues).

When I have forgotten to close the connection the previous day, I can click the "Disconnect" button in my client, but from there on nothing happens.
I always have to kill the client as well as the OpenVPN service, then restart the OpenVPN service and start the client to get things going again.

Possible hint for troubleshooting:
One things that might be "special" in our setup, is that the certificates expire every night at 04:00:00.
When the expiry is related to the issue that we see, then others might not see it that often as we do.
The issue in that case would be: the certificate expires during the time that the computer is asleep.
Maybe this helps in pinpointing the issue.

**Comment by mmakaay** [comment]
I have noticed that things will work if I don't try to open the Windows client, but instead go to the task manager after waking up my computer, and killing the Letsconnect client from there. If I do that, then I won't have to touch the OpenVPN service.
If I do open the client, then both client and server seem to lock up and I have to kill both to get things going.

**Comment by rozmansi** [comment]
I was not able to reproduce this issue. Was playing with a more recent eduVPN client, so the issue might be implicitly solved by other upgrades, or I am doing something different.

Nevertheless, I have released an updated client here: https://github.com/Amebis/eduVPN/releases/tag/1.0.37

Please upgrade and report back if the issue persists.

**Comment by mmakaay** [comment]
I have upgraded and the last few days, I am directed to the VPN authentication website after waking up the computer. Maybe it's a bit early to celebrate, but things certainly look a lot better currently.
Hey @vosdev , can you confirm the change in wake-up behavior?

**Comment by mmakaay** [comment]
This morning, I ran into the issue again, unfortunately.
The client did not reconnect, showed no IP-adresses and let me click the Disconnect button.
Clicking the button yielded no results, except for a hanging client.
I did the kill client, restart OpenVPN cycle to get it up and running again.

**Comment by rozmansi** [comment]
The 2.0-RC should be stable enough for broader testing now. As it is a completely redesigned release with a different token (certificate) expiration, you might give it a try. Download and install it from here: https://github.com/Amebis/eduVPN/releases/tag/1.255.8

**Comment by mmakaay** [comment]
I installed the new version and step 1 of the testing was successful: I can still connect to the VPN   😄👍
I will monitor its behavior on wake-up. Thanks for the heads up!

**Comment by mmakaay** [comment]
I'm running the RC for about two weeks now, and I haven't had any problems since.
As far as I'm concerned, 2.0 fixes the issues.

**Comment by rozmansi** [comment]
Thank you for your feedback.
