### ISSUE TITLE
Start eduVPN @ boot

### ISSUE THREAD

**Issue by mkoelewijn** [Amebis/eduVPN#167]
Add the option to the installer, and the setting within the eduVPN app, to start the eduVPN client when windows boot (startup). Because now the user must configure this like this:

![add app to run automatically at startup](https://user-images.githubusercontent.com/26085443/123955848-63628200-d9aa-11eb-80fd-a3b82d83da63.jpeg)

After i did this please also notice the name in the startup list in windows:

![Startup apps windows](https://user-images.githubusercontent.com/26085443/123955913-77a67f00-d9aa-11eb-9637-d25503437f33.jpeg)

**Comment by fkooman** [comment]
Previously, partly solved #123

**Comment by rozmansi** [comment]
Side note: We're not talking about starting at Windows boot, but starting when user logs in.

It is difficult to add any options to the installer. It has very limited GUI. My proposal is to install eduVPN to startup on logon (minimized on system tray) every time. Then have a knob in the settings to turn this off.

**Comment by fkooman** [comment]
> Side note: We're not talking about starting at Windows boot, but starting when user logs in.

My observation: the VPN _does_ connect before the user logs in, i.e. provides their credentials. But maybe that is intentional?
