### ISSUE TITLE
force tcp + only available udp remotes gives confusing error

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#174]
![image](https://user-images.githubusercontent.com/616885/134149960-53de67cf-3d28-40ba-bcbf-d8e69bce6c75.png)

But maybe this makes sense when considering OpenVPN internals... not sure.

<details>
<pre>
OpenVPN reported fatal error.
No usable connection profiles are present
</pre>
</details>

**Comment by rozmansi** [comment]
True, OpenVPN's built-in message when all the `--remote` endpoints from .ovpn were refused is a bit over generic. It would not suggest user that the "Force TCP" setting is probably the reason.

When parsing the .ovpn, the OpenVPN internals raise `REMOTE` notification for each `--remote` in .ovpn. Our notification handler gets called and responds to accept/refuse individual `--remote` line. Unfortunately, it doesn't know the total number of `--remotes`. So, eduVPN client doesn't know it actually refused all the `--remotes` and handle this situation gracefully with a more meaningful message.

As the "No usable connection profiles are present" string is hard-coded into OpenVPN, the simplest way would be to strcmp() the error returned from OpenVPN and convert it into a friendlier message.

**Comment by fkooman** [comment]
This is no longer an issue with APIv3 I guess?

**Comment by rozmansi** [comment]
Ahh. :) Cool. I guess I should have gone straight into APIv3 implementation, rather than addressing issues on the tracker first.
