### ISSUE TITLE
support for Minisign prehashed signature format

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#178]
Minisign 0.10 was released over the weekend and defaults to using prehashed signatures. See [here](https://jedisct1.github.io/minisign/#signature-format) for more information about prehashed signatures. In the future "legacy" signatures will be removed from minisign, so we should probably switch to prehashed signatures a.s.a.p. You could potentially leverage any of the [listed](https://github.com/jedisct1/minisign/#additional-tools-libraries-and-implementations) implementations if they are of sufficient quality and support prehashing... 

The [Server Discovery](https://github.com/eduvpn/documentation/blob/v2/SERVER_DISCOVERY.md) documentation has also been [updated](https://github.com/eduvpn/documentation/commit/4a8f7f835ac40c8f13d884e2df64262e62f8d3c1) to mention prehashed signatures.

Steps:
- [x] make sure prehashed signatures are supported
- [ ] add option to reject non-prehashed signatures, compare to `-H` flag in Minisign (to be activated in the future)

**NOTE**: this issue was created in all eduVPN application repositories.

**Comment by rozmansi** [comment]
Prehashed Minisign signatures were supported from day 1: https://github.com/Amebis/eduVPN/blob/master/eduVPN/Xml/Response.cs#L245

**Comment by rozmansi** [comment]
@fkooman, bump me please when all online content is Minisigned as prehashed, as I would prefer to completely remove the support for legacy signatures from the code then.
