### ISSUE TITLE
Support Windows 11

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#181]
Some users report [unconfirmed, exact problems not known] eduVPN/Let's Connect! does not work on Windows 11.

Unfortunately I am unable to test myself due to the (artificial) difficulty Microsoft introduced preventing me from running it as a test VM.

**Comment by rozmansi** [comment]
I have just tested to confirm the `master` version of client works on Windows 11 as it should.

Waiting for VirtualBox 7 which should support Windows 11 to test the installed client survives the Windows 10 → 11 upgrade as well.

Unless there are some specific issues with Windows 11, I am closing this for the time being.
