### ISSUE TITLE
credits in app

### ISSUE THREAD

**Issue by TanguiC** [Amebis/eduVPN#185]
Hello - in the credits page (after the user clicks on the question mark):
- there should be: "The Commons Conservancy" instead of "The Commons Conservancy eduVPN Programme" 
- SURF logo should be removed
Thanks!

![screenshot](https://user-images.githubusercontent.com/17877878/150802902-ea09f4be-febb-48d4-b806-ca61b258ae5a.jpeg)

**Comment by rozmansi** [comment]
We have _"Copyright: 2021-2022 The Commons Conservancy eduVPN Programme"_ in all source code colophones. Probably it should be _"Copyright: 2021-2022 The Commons Conservancy"_ now, right?

**Comment by fkooman** [comment]
2017-2022?

**Comment by rozmansi** [comment]
> 2017-2022?

Right. The Copyright year varies from source file to source file. The first year is the year particular file was introduced, the last year is the year I remembered to bump the Copyright notice. :)
