### ISSUE TITLE
switch to /.well-known/vpn-user-portal as per API spec

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#186]
From `/info.json` -> `/.well-known/vpn-user-portal`.

**Comment by rozmansi** [comment]
This has already been done here: https://github.com/Amebis/eduVPN/commit/be0c4aae08cd571d168b7c0a812c846c1ff3644f#diff-9b33564b069c33534184c3dda7970f870f82bf9f8eaab0a15b9cc73f12a2f332L169

The issue appeared because eduVPN.dll binary was in use when upgrading and was not updated.
