### ISSUE TITLE
"Force TCP" switch button color does not change

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#19]
It is not clear if the "Force TCP" is actually on or off.

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/30485791-ccee704a-9a2e-11e7-9303-cf0131976680.png)


I assume to the right is "on", to the left is "off"?

**Comment by rozmansi** [comment]
Believe me, I had changing colours in my working copy, but scraped them before commit.

I shall ask Sebas to provide an official "off" checkbox screen shotfirst.

**Comment by rozmansi** [comment]
![force_tcp_off](https://user-images.githubusercontent.com/6889694/30509573-254f58dc-9ab4-11e7-8092-e117ab92d1c0.png)

**Comment by rozmansi** [comment]
Sebas confirmed the proposed "off" state.
