### ISSUE TITLE
reset eduVPN profile

### ISSUE THREAD

**Issue by rudgab** [Amebis/eduVPN#192]
Hi, on all (not windows) version I can reset the app. Not on my windows 2.1 (latest) and I´m getting the old installed profile from my former installation when I remove the old version and reinstall with 2.1. Is there a complete remove docu, where these old profiles are stored?

Sincerely

Rudi G.

**Comment by rozmansi** [comment]
This is related to #187.

Open a Command prompt and run this: `rd /s "%LOCALAPPDATA%\SURF"`

Due to popular demand, I am thinking about building this into the client GUI somehow.

**Comment by rudgab** [comment]
Thanx, that did it.

R.G.

Von meinem iPhone gesendet
