### ISSUE TITLE
Installation via winget

### ISSUE THREAD

**Issue by ottnorml** [Amebis/eduVPN#193]
Hi together,

I have added eduVPN to the Microsoft community Windows Package Manager manifest repository (see https://github.com/microsoft/winget-pkgs/pull/61595), so it can be installed via this handy CLI command: `winget install SURF.eduVPNClient`. 

I hope this is OK for you, since I'm not the owner of this software. Also I am not sure if 
1. this is the right place to ask for and to add documentation and
2. how to maintain the winget manifest best.

**Comment by ottnorml** [comment]
> The eduVPN project originated at SURF, but it migrated to GÉANT later. So, naming the package SURF.eduVPNClient might not be the best choice. Maybe @efef can shed some light here.

To create the manifest, I used the tool [winget-create](https://github.com/microsoft/winget-create), which reads the installer's metadata. I saw that the migration was in progress, but since at the time of execution the metadata still contained SURF, I kept it. How to proceed when the author of a software changes, I have asked here (see https://github.com/microsoft/winget-pkgs/discussions/62488).

**Comment by russellbanks** [comment]
Hi, I came across this from the discussion on winget-pkgs.

> How to proceed when the author of a software changes.

I would suggest making a PR to remove the old version (or several PRs if there are several versions - a PR for each version removal) and then resubmitting the package under the new author. For example, I did this recently, moving `BanDev.Lux` to `JackDevey.Lux`.

Removing the package: [#62914](https://github.com/microsoft/winget-pkgs/pull/62914)

Resubmitting the package under the new author: [#62913](https://github.com/microsoft/winget-pkgs/pull/62913)

> Second, I am not sure that we want downloads pointing to GitHub, but rather to https://app.eduvpn.org/windows/. (Thou, there are no .msi files published there.) Mind that this GitHub repository is where the Windows client development is taking place and I publish releases here first. But, the releases here are considered as _"pending revision"_ until they are finally published on https://app.eduvpn.org/windows/.

Despite this, I would still suggest using GitHub releases for this. The reason for this is if the MSI files are published here, then this is what WinGet will use and will be able to use the easiest (MSI's are the most desirable).

Furthermore, having the releases under GitHub releases means that there is a stable link that won't change throughout releases (other than changing the version number in the URL, etc) and we can ensure that no rate limits or api limits will be reached by downloading the files from a separate website.

Finally, having the releases on GitHub means better integration with other WinGet automation tools, if that is something that is chosen in the future, such as the [WinGet Releaser GitHub Action](https://bittu.eu.org/docs/wr-intro/) which can automatically make a pull request to the winget-pkgs repository on every release so there is little to do on the maintainer's part.

**Comment by rozmansi** [comment]
1. Author can remain SURF. Got a confirmation it's OK.
2. I understand the GitHub download choice and I agree with it.

Thank you for your contribution.

**Comment by rozmansi** [comment]
I have automated the winget manifest creation and will make winget-pkgs PRs from now on each (non pre-) release.
