### ISSUE TITLE
VPN pre-login possible?

### ISSUE THREAD

**Issue by Lukas-UAUX** [Amebis/eduVPN#195]
Would it be possible to get eduVPN to connect pre login (Windows)? 

Maybe similar to the way that Cisco AnyConnect (SBL) provides? If this module is installed, you get an additional icon next to the regular network-icon at the login screen. If you click on it the vpn app shows up, and you can connect to your network. 

This would be a really nice feature, for example to have an active connection to the ActiveDirectory at login, for example for a new user or if the mobile account expired - and GPO of course...

**Comment by rozmansi** [comment]
I'm afraid this is not possible with the classic Windows VPN clients. However, your feature suggestion makes sense and I will investigate possibilities. See if there is a chance to implement it.

**Comment by Lukas-UAUX** [comment]
I have a very, very faint memory, that Cisco AnyConnect does it via a "login provider" (or is it credential provider?) Maybe that would be the trick

**Comment by efef** [comment]
We are actually working on pre-provioning. The work done so far is documented here: https://github.com/FlorisHendriks98/eduVPN-provisioning
In this page we describe how to leverage MS AD (and PKI) to do preprovioning. However at the moment we are working on another path:
 use MS intune in combination with an new eduVPN server API call to preprovision Windows and macOS devices. 

If you like to be involved @Lukas-UAUX  please email us: eduvpn-support@lists.geant.org

**Comment by Lukas-UAUX** [comment]
That sadly doesn't look like it would fit our use case or environment. For one thing the user must be able to control the vpn and we have multiple networks/profiles that can not be tied to a machine identity but user only. Additionally eduroam which is considerably important at a university is a user-config network that starts after login.

**Comment by rozmansi** [comment]
We are moving to https://codeberg.org/eduVPN/windows/issues/195
Sorry for the inconvenience.
