### ISSUE TITLE
unable to connect to interactive service

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#196]
As reported through mail:

> We switched completely to eduVPN (v2) now, which is working very well!
> Thank you for the good work.
> 
> Problem:
> 
> We get a lot of incidents from Windows Users, which get the following - German - error message:
> 
> "System.AggregateException: Interaktiver Dienst gescheitert. ---> Die Verbindung zum interaktiven Dienstopenvpn$eduVPN\service ist fehlgeschlagen. Vergewissern Sie sich bitte, dass der Dienst gestartet ist. ---> System.IO.IOException: Das Zeitlimit für die Semaphore wurde erreicht.“
> 
> Our workaround by now is:
> 
> - Uninstall the eduVPN client.
> - Install all upcoming updates of your Windows computer.
> - Restart the computer.
> - Install the eduVPN client.
> 
> This helps in most of the incidents.
> 
> Questions:
> 
> Did you ever come across this error?
> 
> What is the reason for the error?
> 
> Is there an other - easier - way to fix this?
> 
> Any help or directions will be highly appreciated.

**Comment by rozmansi** [comment]
This has been fixed in fc9dc598335bb0c7ce7d99ae392758b88eff4d46. The issue was caused in sequence following the issue #194, which was fixed in 70552c5cb2253d6c2ccbf7dca542ea1041540255.
