### ISSUE TITLE
Option to disable self-update

### ISSUE THREAD

**Issue by hm-tobias** [Amebis/eduVPN#198]
Hello!

Is it possible to disable the self-update hints and workflow?

Thx
Tobias

**Comment by rozmansi** [comment]
Yes, it is... Take a look [here](https://github.com/Amebis/eduVPN/blob/master/doc/Deployment.md#keeping-eduvpn-client-up-to-date).

Basically, you create a `HKEY_LOCAL_MACHINE\SOFTWARE\SURF\eduVPN\SelfUpdateDiscovery` value of type `REG_SZ` and set it to an empty string or some invalid URL.
