### ISSUE TITLE
Reconnect after power-saving mode

### ISSUE THREAD

**Issue by hm-tobias** [Amebis/eduVPN#199]
Hi!

With version 3.x, the automatic reconnect no longer works after a power-saving mode (Windows 10). I even remembered that automatic reconnect worked with version 2.x after a reboot, but I'm not sure about this. 

My question is is this due to server settings or is it client related?

Thanks a lot
Tobias

**Comment by rozmansi** [comment]
Confirming I can reproduce it. Working on a fix.

**Comment by rozmansi** [comment]
I have released [3.1.1](https://github.com/Amebis/eduVPN/releases/tag/3.1.1) which fixes this.

Thank you for reporting it. Your feedback is welcome: do give it a try, please.

**Comment by hm-tobias** [comment]
Thank you for the quick help.

The fix works for reconnecting after sleep mode. 

Should it also work after a reboot? This does not work at the moment. EduVPN starts with the following window. After clicking on the university, the previous connection is immediately established. 

![image](https://user-images.githubusercontent.com/105930543/175773187-c45a1c1b-9335-4c50-ab5d-0c2b71d55ac4.png)

**Comment by rozmansi** [comment]
Yes, it should also work after reboot. Under one condition: if you do not disconnect manually before rebooting.

**Comment by rozmansi** [comment]
I have confirmed 3.1.1 to reconnect automatically after a reboot. If you don't experience the same, I am very interested in details why it doesn't.

**Comment by hm-tobias** [comment]
I have made a small video of the current process. 
When rebooting, eduvpn is active. After logging in, EduVPN starts automatically but only connects after manual intervention.

https://user-images.githubusercontent.com/105930543/175948626-957a3ea8-1c3e-4876-b7a9-17e6bfc943b0.mp4

**Comment by rozmansi** [comment]
Wow. I was not able to reproduce this first. Looking at the code, found a path that could lead to this behavior - although had to mock my config .xml by hand it to reproduce it. Preparing a fix...

**Comment by rozmansi** [comment]
Published [3.1.4](https://github.com/Amebis/eduVPN/releases/tag/3.1.4) with fixed auto-reconnect.

**Comment by hm-tobias** [comment]
Works! Thank you for fixing the errors so quickly.
