### ISSUE TITLE
Review and tighten access to .ovpn and .conf.dpapi

### ISSUE THREAD

**Issue by rozmansi** [Amebis/eduVPN#201]
Check and determine least set of ACL required by tunnel config files. Maybe encrypt it with a securely stored key?

**Comment by jwijenbergh** [comment]
For eduvpn-common I'm implementing a method that allows you to customize the encryption method used to store the access/refresh tokens. So the windows client can still use DPAPI and Linux kan use the keyring, e.g. the gnome or kde keyring or something else if available.
