### ISSUE TITLE
Investigate eduvpn-common

### ISSUE THREAD

**Issue by rozmansi** [Amebis/eduVPN#202]
https://github.com/jwijenbergh/eduvpn-common

**Comment by rozmansi** [comment]
Should also resolve #158 and hopefully #159.

**Comment by jwijenbergh** [comment]
I'm currently investigating into implementing eduvpn-common into the Linux client. The API between Go and Python is thus kept up to date the most. An API for the interaction between C# and the Go library was made previously but currently does not reflect the latest Go API. My goal is to thus first get a good implementation in the Linux client and then update the C# code to be used in this client as well. AFAICT Go's `net` module has happy eyeballs support by default

**Comment by rozmansi** [comment]
> My goal is to thus first get a good implementation in the Linux client and then update the C# code to be used in this client as well.

Sure. It's difficult to keep an API up-to-date when everything is still under heavy development and one doesn't even use that API for own purposes.
