### ISSUE TITLE
Update release channel

### ISSUE THREAD

**Issue by bernhardschmidt** [Amebis/eduVPN#203]
As far as I can see the official download and the latest version in the self-update release channel is 3.1(.0). Considering #199 and especially #200, would it be far off to have these rolled out via self-update? Or did I miss something or is the self-update not working for me?

**Comment by rozmansi** [comment]
Self-update was set to 3.0 for about a week, but #199 and #200 made us panic and revert it back to good old reliable 2.1.

With eduVPN user base grown so big it takes a lot of responsibility to push an update. Not an easy decision to make - what if something goes wrong?

We are aware of this situation and are preparing 3.2 release that would also be published as the self-update. Unfortunately, it's holiday season, and we would like to time the release to the moment all developers are available to provide assistance and support should anything turn out wrong.

Thank you for your patience.

BTW, recently I prepared a pre-release self-update channel. If you would like to switch to _the fast ring_, here's [the registry setting](https://github.com/Amebis/eduVPN/files/9092747/eduVPN_Pre-release_Self-update_Channel_registry.zip). You may deploy it to other users of your organization - preferably to the tech-savvy users that are potentially able to recover from any issues found and report them.

**Comment by rozmansi** [comment]
Self-update is now pointing to 3.3 release.
