### ISSUE TITLE
add button to check for update

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#204]
it is not currently possible to (manually) search for an update of the app and you are depending on the automatic timer to trigger it, but it doesn't run always and also not every day, so it is not exactly clear when it would check.

**Comment by sveeke** [comment]
Actually this is something I heard from more users. They ignore the update once (e.g. when they have a important meeting) and after that it sometimes takes days or even longer before another update request appears. Would be great if there was a "Check for updates" button inside the settings view (to not have it clutter the main program interface) that procs the update window.

**Comment by rozmansi** [comment]
Exactly, when user dismisses the self-update prompt it does not reappear for 3 days. The background update check is performed on start of the eduVPN client and on every 24 hours ±10% thereafter. So, basically we're talking about 3-4 days after the client re-prompts the user.

3.2 was published as an self-update and user might got prompted to update but declined it initially. After #205 the 3.2 was removed as an self-update, hence user didn't get prompted to update any more.

Should introduce an "Update" button to the About or Settings page, so a user can trigger an update manually.
