### ISSUE TITLE
Increase minimum vertical app size

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#206]
Ola,

Problem: vertical app size too small to show Connection info.

Screenshot:
![image](https://user-images.githubusercontent.com/12334213/179737580-1323d86f-9b3c-4cd7-b983-3628528e031a.png)

I think this happened because of the "Valid for **80 days and 23 hours**". I *think* in the past this notice would only show itself when the certificate was close to its expiry date. Back then when this notice would show, the vertical app size also was too small for the Connection info. But especially now that the validity is shown always I would just increase the app size a bit to accommodate all text :).

**Comment by rozmansi** [comment]
Sure, I can rise the minimum height of the client window. The minimum size was matched to the initial client GUI design guidelines. After evolving over the time more and more information got onto the connection page, but the minimum height was never adjusted to compensate.

Mind that you may resize the client window yourself. The client will remember its window position and _size_.

**Comment by rozmansi** [comment]
It gets even worse when there are multiple support links:
![image](https://user-images.githubusercontent.com/6889694/183437046-9065a3fa-bf7a-41b1-92e0-03e1269296f1.png)
