### ISSUE TITLE
Update eduVPN build system `ManifestVersion` to 1.2.0

### ISSUE THREAD

**Issue by russellbanks** [Amebis/eduVPN#208]
The latest WinGet `ManifestVersion` is 1.2.0, so the build system should be updated to that.

[Documentation for 1.2.0 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)

**Comment by rozmansi** [comment]
Done in eb1c63a8a51aa9572b56a3b25e3f9c3ec114ad2f
