### ISSUE TITLE
Feature-Request: Use embedded WebView (Edge WebView 2) for browser based authentifications (like SAML)

### ISSUE THREAD

**Issue by Lukas-UAUX** [Amebis/eduVPN#209]
Hi,

would it be possible to implement the use of a (Edge) WebView to allow authentification inside the app windows itself? Using the Browser does work - but it is not very 'elegant' and throws off some users.

**Comment by rozmansi** [comment]
[RFC6749 Section 9](https://www.rfc-editor.org/rfc/rfc6749#section-9) is discussing external or embedded browser to perform authentication. When designing eduVPN it has been agreed to use external browser for the OAuth for the advantages discussed in RFC.
