### ISSUE TITLE
error upgrading to 3.3

### ISSUE THREAD

**Issue by jayymaster** [Amebis/eduVPN#212]
Upgrade to 3.3 (MSI installer) fails if SYSTEM account is used for installation. It is probably again a permissions issue with C:\Program Files\eduVPN\OpenVPN\config. Probably the same problem as described in #205 

The SYSTEM account is used by deployment tools like SCCM to install software.

[eduVPNClient-Update-3.3.log](https://github.com/Amebis/eduVPN/files/9725687/eduVPNClient-Update-3.3.log)

**Comment by rozmansi** [comment]
Examined the log. You are correct.

I will have to introduce more aggressive cleaning of the `C:\Program Files\eduVPN\OpenVPN\config` folder then.

**Comment by rozmansi** [comment]
Whoa, this one was really insane. About 500 new lines of code to make it work. I've tested all the following scenarios to allow seamless upgrade:

1. When MSI is invoked as a SYSTEM, it resets ACL of the config folders and deletes all files inside.
2. When MSI is invoked from an elevated process (e.g. cmd.exe run as Administrator), it impersonates SYSTEM, resets ACL of the config folders and deletes all files inside.
3. When MSI is invoked as an unelevated process but by a user who's member of Administrators group, it spawns a new process elevated, impersonates SYSTEM, resets ACL of the config folders and deletes all files inside.
4. When MSI is invoked as an unelevated process by a user who's not a member of Administrators group, it attempts to reset ACL of the config folders and delete all files inside. However, it will succeed to delete only files owned by the user. If only this user was using the eduVPN client on this computer, it should allow seamless upgrade.

**Comment by rozmansi** [comment]
I have released [3.3.2](https://github.com/Amebis/eduVPN/releases/tag/3.3.2) which you can use to test SCCM deployment over the flawed 3.2 one. It should upgrade correctly now. And also allow later uninstall if needed.

**Comment by jayymaster** [comment]
> I have released [3.3.2](https://github.com/Amebis/eduVPN/releases/tag/3.3.2) which you can use to test SCCM deployment over the flawed 3.2 one. It should upgrade correctly now. And also allow later uninstall if needed.

SCCM deployment works! Thank you!
