### ISSUE TITLE
make deleting server entries more discoverable?

### ISSUE THREAD

**Issue by ghost** [Amebis/eduVPN#223]
There's no way for the user to "discover" how to delete server entries from the app. One has to know that a right click is required. Not everybody knows this.

I am not sure how common this problem is, or whether or not we have to assume the user knows this? Also not sure how to improve this? Perhaps with an "edit" button or something that allows you to "select" the entries and then delete them?

> BTW, the right click "delete" option in the Windows/macOS client (and 
long tip on Android) is very good hidden and not very intuitive. Most of 
the users (including myself) did not find that option by themselves. 
Perhaps it could be made more user-friendly?

**Comment by Lukas-UAUX** [comment]
Yes, I would also suggest a trashcan icon for deleting and it should be greyed out if that connection is pre-defined and can not be deleted.

(Would also be cool if this can be unified across all plattforms...)

**Comment by rozmansi** [comment]
We are moving to https://codeberg.org/eduVPN/windows/issues/223
Sorry for the inconvenience.
