### ISSUE TITLE
Loading of API endpoints failed

### ISSUE THREAD

**Issue by Relojuca** [Amebis/eduVPN#224]
Hi People!

I tried to use eduVPN. However, after trying to run the app several times.  I always get the same error:

System.AggregateException: Loading of API endpoints failed. ---> System.AggregateException: Downloading from web failed. Please check your internet connection. ---> System.Net.WebException: Anulada la solicitud: No se puede crear un canal seguro SSL/TLS.
   en System.Net.HttpWebRequest.GetResponse()
   en eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String responseType, Response previous, CancellationToken ct)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String responseType, Response previous, CancellationToken ct)
   en eduVPN.Models.Server.GetEndpoints(CancellationToken ct)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en eduVPN.Models.Server.GetEndpoints(CancellationToken ct)
   en eduVPN.ViewModels.Pages.AuthorizationPage.OnRequestAuthorization(Object sender, RequestAuthorizationEventArgs e)
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en eduVPN.ViewModels.Pages.AuthorizationPage.<TriggerAuthorizationAsync>d__8.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en eduVPN.ViewModels.Pages.SearchPage.<<get_ConfirmOrganizationSelection>b__25_0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Nº de excepción interna 0) System.AggregateException: Downloading from web failed. Please check your internet connection. ---> System.Net.WebException: Anulada la solicitud: No se puede crear un canal seguro SSL/TLS.
   en System.Net.HttpWebRequest.GetResponse()
   en eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String responseType, Response previous, CancellationToken ct)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String responseType, Response previous, CancellationToken ct)
   en eduVPN.Models.Server.GetEndpoints(CancellationToken ct)
---> (Nº de excepción interna 0) System.Net.WebException: Anulada la solicitud: No se puede crear un canal seguro SSL/TLS.
   en System.Net.HttpWebRequest.GetResponse()
   en eduVPN.Xml.Response.Get(ResourceRef res, NameValueCollection param, AccessToken token, String responseType, Response previous, CancellationToken ct)<---
<---

My machine uses windows 10. Could anyone please help me to fix it?

Regards

**Comment by rozmansi** [comment]
Hi!

Your version of the eduVPN client is using .NET Framework web client internally to contact _https://_ servers. Therefore, the client version you are using does not support the TLS v1.3. The error you are experiencing typically occurs when the organization you are trying to connect to is supporting only the latest TLS standards namely TLS v1.3 and provide no fallback to previous versions.

This issue has been fixed by replacing .NET Framework web client with Golang one and remains to be released yet. Fortunately, you can already download the 3.255.x (4.0 prerelease) eduVPN client [here](https://github.com/Amebis/eduVPN/releases) and install it. These eduVPN client versions have mostly the same functionality and are compatible with existing eduVPN servers. So, you are perfectly safe to use it.

Please, give it a try and confirm if it resolves your issue.
