### ISSUE TITLE
since version 3.3.6 the UI does not show the validity token anymore

### ISSUE THREAD

**Issue by jayymaster** [Amebis/eduVPN#225]
Unfortunately, since several versions the validity token is no longer displayed in the UI. It is also missing in the current version 3.255.2. The last working version is 3.3.6. Could the validity token please be implemented again?

Version 3.255.2 without validity token
![eduVPN_without_validity_token](https://github.com/Amebis/eduVPN/assets/115155768/c400160a-febc-40b3-951e-56e482d18535)

Version 3.3.6 with validity token
![eduVPN_with_validity_token](https://github.com/Amebis/eduVPN/assets/115155768/3784070c-5018-478e-a12a-ed3a772a925e)

**Comment by jwijenbergh** [comment]
What about 3.4? 3.255.2 is a pre-release whereas 3.4 is the latest official release

**Comment by jayymaster** [comment]
With 3.4 unfortunately the same

**Comment by rozmansi** [comment]
This is intended behavior as per documentation: https://github.com/eduvpn/documentation/blob/v3/API.md#session-expiry

Documentation invented the session expiration countdown timer should be shown the last 24 hours before expiration only.

Do you have any reasons why you would need to know the expiration before that time?

**Comment by jayymaster** [comment]
Not really. 

I just noticed the new behavior of the client and it might lead to an increased number of requests from our users. 

If this is the intended behavior, the issue can be closed.
