### ISSUE TITLE
option to allow local area network traffic when using wireguard

### ISSUE THREAD

**Issue by borenius-dfn-de** [Amebis/eduVPN#226]
By default the wireguard client seems to block traffic to the local area network which inhibits people from using their local network resources while being connected to the VPN.

Something like the "Block untunneled traffic (kill-switch)" in the Wireguard client from wireguard.com would be nice.

**Comment by rozmansi** [comment]
Sorry for a late reply.

Blocking the local traffic (or not blocking the local traffic) **can be configured on the eduVPN server in the profile configuration**.

Namely: VPN server admin/your institution chooses this. If they do so by their policy and their security concerns, VPN client must obey that. Please, consult your institution if they could reconsider their policy or provide additional profile that could allow local traffic too.

**Comment by borenius-dfn-de** [comment]
Thanks for the reply! I wasn't successful in finding any information on that. There is the 'oBlockLan' but the comment says "OpenVPN Only". And searching through the source code does not reveal any wBlockLan parameter. The work around for us at the moment is

'defaultGateway' => false,
'routeList' => [
         '0.0.0.0/1',
         '128.0.0.0/1',
         '::/1',
         '8000::/1'
],

Works for us, but looks ugly to me ;-)
