### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by vbandaragoda** [Amebis/eduVPN#230]
Hello Guys, 

Since yesterday I can't start the Windows and IOS applications. 
On the Windows app, it didn't respond to the selected country button. 

After some time it shows the following timeout message.
 
![image](https://github.com/Amebis/eduVPN/assets/66273939/0a23f1b4-d2bc-4ec5-8071-78ac202d5f89)

On the IOS app, it tries to contact the server but after a few seconds it shows the timeout alert as well. 

![edu](https://github.com/Amebis/eduVPN/assets/66273939/11286c14-523d-44e8-a3bf-2c96d1473e9f)

Thanks

**Comment by rozmansi** [comment]
I believe this is/was a network issue. Maybe eduVPN server `eduvpn.ac.lk` is down? Maybe the network is down?

This is not a client issue. The client only explains it cannot reach the server.
