### ISSUE TITLE
run eduVPN minimized on startup

### ISSUE THREAD

**Issue by hueldoeu** [Amebis/eduVPN#231]
I like a fresh restart sometimes on Windows10/11 and when the restart is done, I can see my Desktop with some files and nothing else. I have lots of RAM and don't care about all the programs and processes inthe background. Therefore I enjoy starting programs in the background and open them when I need them. How to?

**Comment by rozmansi** [comment]
eduVPN client can be configured to startup automatically when Windows starts and user signs in:
![image](https://github.com/Amebis/eduVPN/assets/6889694/d14764ee-66cf-4214-a6e6-4a9a2cbb497e)

Also on auto start, the client will be minimized in the system tray in the right bottom corner of the screen:
![image](https://github.com/Amebis/eduVPN/assets/6889694/589b022a-4655-414a-8577-589591dc8c8e)

**Comment by hueldoeu** [comment]
thx. i had a little problem with cmd => winget upgrade SURF.eduVPNClient and simply installed the newest .exe from here https://github.com/Amebis/eduVPN/releases now cmd => winget upgrade looks better (no SURF.eduVPNClient anymore).

**Comment by hueldoeu** [comment]
> eduVPN client can be configured to startup automatically when Windows starts and user signs in:
> 
> Also on auto start, the client will be minimized in the system tray in the right bottom corner of the screen: ![image](https://private-user-images.githubusercontent.com/6889694/300521589-589b022a-4655-414a-8577-589591dc8c8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NzQxMTQsIm5iZiI6MTcwNjU3MzgxNCwicGF0aCI6Ii82ODg5Njk0LzMwMDUyMTU4OS01ODliMDIyYS00NjU1LTQxNGEtODU3Ny01ODk1OTFkYzhjOGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMDAxNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFmY2YyN2U5NmU2NmQ5YzZlODg2MzJjOGNiMWMxN2MzZjRjYzg4NjQyZWQ1NWM3YzE0MDZjNGNhMTM0ZWZmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.z12EdHMoaWHLg-tb4YYTsbOzsfZxReNkWnsfWrwNQ_M)

you should take a look at your windows security also drag the meet now icon next to eduvpn-symbol or windows security symbol and probably deactivate the hover of news and interests (Cold...)

**Comment by rozmansi** [comment]
> you should take a look at your windows security also drag the meet now icon next to eduvpn-symbol or windows security symbol and probably deactivate the hover of news and interests (Cold...)

I understand your suggestion, thanks. I do as you suggested on my working computers. However, this screenshot was taken on a vanilla Windows 10 virtual PC I am keeping untouched with a purpose. Everything is set to default for testing purposes, making screenshots, testing out-of-the-box experience etc.
