### ISSUE TITLE
Browser window fails to open - fallback suggestion

### ISSUE THREAD

**Issue by J-a-x-u** [Amebis/eduVPN#234]
I sometimes get reports from users that the browser window does not open. Unfortunately I do not know the reason for this or am able to debug this as I myself never encountered this, but I would like to **suggest adding a text box with the necessary link which can then just copied and pasted to a browser windows as a simple fallback**.

**Comment by rozmansi** [comment]
Thanks for reporting this. Maybe user has no default browser set (yet)? Maybe user installed browser B and made it default, then uninstalled it and is using back browser A? Will try to reproduce to research, how does ShellExecute behave. (Client is using ShellExecute to spawn URL.)
Your proposal with a fallback is reasonable. Will implement it when the client detects URL launch failed.

**Comment by J-a-x-u** [comment]
I was also thinking of an uninstalled browser that was the default and tried to reproduce, but failed. eduVPN/Windows always behaved as expected. In the case if no default browser, windows just asked for which browser to open. But on the reporting users system simply nothing happens at all.
(I guess the nextcloud guys ended up in the same position, gave up and implemented the copy&paste link fallback :wink:)

**Comment by rozmansi** [comment]
Before:
![image](https://github.com/Amebis/eduVPN/assets/6889694/69619667-cc57-4a82-9db0-ae52d19de3f9)

After:
![image](https://github.com/Amebis/eduVPN/assets/6889694/68cf35a0-870a-4303-b40e-54499a5c629c)
