### ISSUE TITLE
Support for the "setMTU" Setting in Wireguard

### ISSUE THREAD

**Issue by xamor** [Amebis/eduVPN#236]
Using the Windows eduVPN client the setMTU setting in wireguard seems to bee ignored. The MTU ist still on 1420.

 MTU  MediaSenseState      Bytes In     Bytes Out  Schnittstelle
----------  ---------------  ------------  ------------  -------------
      1420                1         92207          8377  eduvpn.uni-konstanz.de

There are some cases we need a lower MTU (vodafone in germany using ds-lite for example).

**Comment by rozmansi** [comment]
The MTU is configured on the eduVPN server side:
https://docs.eduvpn.org/server/v3/wireguard.html#setting-the-mtu

Server prepares .ovpn/wg-quick.conf that eduVPN client passes on to OpenVPN/WireGuard.

**Comment by xamor** [comment]
Yes, i configured it on the server side, so it seems to work on android but not on windows. The mtu is left on 1420 in windows but on server side it is configured  setMtu => 1280

**Comment by rozmansi** [comment]
Will look into it. See where this gets lost.

**Comment by rozmansi** [comment]
Almost forgot: Thanks to report it.

**Comment by rozmansi** [comment]
Looking into this and eduVPN client does set interface MTU:
![image](https://github.com/Amebis/eduVPN/assets/6889694/d0092582-cf1c-40f1-a254-f21ee88aba28)

Can you activate WireGuard connection using eduVPN client and run `netsh interface ipv4 show subinterfaces` on your PC to examine the MTU set on your eduVPN server matches the MTU set on the WireGuard interface, please?

**Comment by rozmansi** [comment]
Also, can you login to https://eduvpn.uni-konstanz.de and create a WireGuard profile there. See if it has the MTU line:
```
[Interface]
MTU = nnnn
```

**Comment by xamor** [comment]
I checked my config again, so i think i found my mistake. "setMtu" is a global Wireguard option... 
I still don't know why it worked on android but now it is working.
I' am Sorry for my mistake and thank you for your help!

You can close this bug report.

**Comment by rozmansi** [comment]
Appreciate your feedback. Thanks.
