### ISSUE TITLE
Loading of API endpoints Failed on V3.6 / Your computer Did not install any windows updates for While V3.255.15 ( My pc lattes windows 10)

### ISSUE THREAD

**Issue by kavindaBanuka** [Amebis/eduVPN#239]
![Screenshot_1](https://github.com/Amebis/eduVPN/assets/117173811/d2a9dc7d-b09b-4eb3-8f2d-d55ccbfd2464)
![Screenshot_2](https://github.com/Amebis/eduVPN/assets/117173811/52bb0433-ccf6-4999-a4ea-29a2a37942bd)
![Screenshot_3](https://github.com/Amebis/eduVPN/assets/117173811/99e9647d-3c63-4d49-bf90-728dc76b0dd8)

What can i do . Please Help Me

**Comment by rozmansi** [comment]
> ![Screenshot_1](https://private-user-images.githubusercontent.com/117173811/318294970-d2a9dc7d-b09b-4eb3-8f2d-d55ccbfd2464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzg3MTcsIm5iZiI6MTcxMjA3ODQxNywicGF0aCI6Ii8xMTcxNzM4MTEvMzE4Mjk0OTcwLWQyYTlkYzdkLWIwOWItNGViMy04ZjJkLWQ1NWNjYmZkMjQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxNzIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzVmZTBhMDBiNzQzYTQ1OWJiYjAzZTliOTBjYTU3MjcwNDk5OWQ5NTQ0ZWMxM2M5ZWJkNjVjOWIyMjBlYjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jrxvUqRkdhDVWvIFnXbe31Xx0_ygGWB1J5z5Q7kEp1Q)

Sri Lanka server is still down. I have asked other people on eduVPN project, and they assured me they have notified Sri Lanka server maintainers. It is nothing you can do but wait. Or complain to Sri Lanka server maintainers. Here's the e-mail: https://status.eduvpn.org/ → (LK) → eduvpn@learn.ac.lk

> ![Screenshot_2](https://private-user-images.githubusercontent.com/117173811/318294973-52bb0433-ccf6-4999-a4ea-29a2a37942bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzg3MTcsIm5iZiI6MTcxMjA3ODQxNywicGF0aCI6Ii8xMTcxNzM4MTEvMzE4Mjk0OTczLTUyYmIwNDMzLWNjZjYtNDk5OS1hNGVhLTI5YTJhMzc5NDJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxNzIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzQ2NWQ3ZWZhYjc2NWMwMmUwMTZkYzBmOGM2YWU3NzhmZjI3OWY4NDVhMzE5YjE0NjdiMTk5ZTg5ZjdiZmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SdgCY0k6g68sUn9bDxKA7XhnDTz3SwEQiKo1MxeuI5s) !

Are you sure your PC is the latest Windows 10? This message is advisory only – you may ignore it. But if you read it carefully, it says your computer hasn't installed Windows Updates for a while. Check your PC Settings → Windows Update → View Update History:
![VirtualBox_win10_02_04_2024_19_34_32](https://github.com/Amebis/eduVPN/assets/6889694/c4dff79e-30f3-4395-912f-7fd3501fd28d)

If you do have some updates installed in the past few months, but eduVPN client is still giving you the message above, please let me know to investigate.

> [Screenshot_3](https://private-user-images.githubusercontent.com/117173811/318294974-99e9647d-3c63-4d49-bf90-728dc76b0dd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzg3MTcsIm5iZiI6MTcxMjA3ODQxNywicGF0aCI6Ii8xMTcxNzM4MTEvMzE4Mjk0OTc0LTk5ZTk2NDdkLTNjNjMtNGQ0OS1iZjkwLTcyOGRjNzZiMGRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQxNzIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjY5MDg0ZWMwNTAyNWQ2Y2ZiZDA1M2IyYWY4ODBiNGRjZmI5N2FlODAzYjllYmNjMjFmODU5OWFkZTVkNzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DW_nVNymXfCP3k8KCwKiX01ihNcLAKx5eSKufYeivmo)

The same reason as your first screenshot: Sri Lanka server is down.
