### ISSUE TITLE
Terminate connection with right mouse click in govVPN Windows client

### ISSUE THREAD

**Issue by govroam** [Amebis/eduVPN#240]
just like MacOS, as discussed with Rogier

**Comment by efef** [comment]
<img width="335" alt="Screenshot 2024-04-05 at 22 04 25" src="https://github.com/Amebis/eduVPN/assets/3393474/9ff0314a-f62b-41e2-8e01-7999b9f2d7eb">
example from macOS

**Comment by efef** [comment]
Idea is to be able to start/stop via systray, for macOS you can even switch between profiles

on macOS when I click on the active profile, the VPN disconnects that profile

Would be nice to have on Windows too

**Comment by rozmansi** [comment]
Thanks for your suggestion. This is a duplicate of #111. I reopened it and added it on 4.x TODO.

**Comment by govroam** [comment]
great and fast work! THanks
