### ISSUE TITLE
winget upgrade SURF.eduVPNClient never really worked

### ISSUE THREAD

**Issue by hueldoeu** [Amebis/eduVPN#241]
![image](https://github.com/Amebis/eduVPN/assets/11273667/a966053a-1d11-414d-a896-1508bc283c48)
therefore i've always have to come here, download the .msi and install it manually.

**Comment by hueldoeu** [comment]
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.

**Comment by rozmansi** [comment]
Thanks for reporting this.
