### ISSUE TITLE
eduvpn_common

### ISSUE THREAD

**Issue by aloispichler** [Amebis/eduVPN#242]
Hello. I am on arch, and eduVPN stopped working; since today, `eduvpn-gui` does nothing, but reports the following error:
```
Traceback (most recent call last):
  File "/usr/bin/eduvpn-gui", line 5, in <module>
    from eduvpn.ui.__main__ import eduvpn
  File "/usr/lib/python3.12/site-packages/eduvpn/ui/__main__.py", line 9, in <module>
    import eduvpn_common.main as common
ModuleNotFoundError: No module named 'eduvpn_common'
```
I already have reinstalled eduVPN via AUR, without success. 
Any idea what went wrong and how to resolve the problem?
Thanks in advance.

**Comment by rozmansi** [comment]
This repository is a fork of https://codeberg.org/eduVPN/eduvpn-common. Please, submit your issue report there. Thank you.

**Comment by aloispichler** [comment]
For all who read this thread: this issue is caused by the new python version and 
```
sudo cp -r /usr/lib/python3.11/site-packages/eduvpn_* /usr/lib/python3.12/site-packages/
```
resolves the problem.
