### ISSUE TITLE
TunnelFailoverTest: int overflow leads to ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by bbrauns** [Amebis/eduVPN#244]
Hey everyone,

My workstation is on Windows 11 and the client unexpectedly crashed with an `ArgumentOutOfRangeException`. Windows EventView showed:

```
Anwendung: eduVPN.Client.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ArgumentOutOfRangeException
   bei System.Net.IPAddress..ctor(Int64)
   bei eduVPN.ViewModels.VPN.Session.<.ctor>b__77_1()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()
```

The issue seems to be that casting `tunnelAddress.Address` to `int` can result in an overflow. See image below. Aside from that `IPAddress.Adress` is marked as obsolete and should be replaced by `GetAddressBytes` [1].

![image](https://github.com/Amebis/eduVPN/assets/6813310/0c0d53ab-268a-4bfa-88c6-8e9e4faab3ab)

I am not familiar enough with the calculation of IP addresses and subnet masks, but replacing line 444 with something like the following should help:
```csharp
 var addressBytes = tunnelAddress.GetAddressBytes();
 var unicastMaskBytes = unicast.IPv4Mask.GetAddressBytes();
 var maskBytes = new byte[] { 0, 0, 0, 1 };
 for (var i = 0; i < addressBytes.Length; i++)
 {
     addressBytes[i] = (byte)(addressBytes[i] & unicastMaskBytes[i]);
 }
 for (var i = 0; i < addressBytes.Length; i++)
 {
     addressBytes[i] = (byte)(addressBytes[i] | maskBytes[i]);
 }

 gateway = new IPAddress(addressBytes).ToString();
```

[1] https://learn.microsoft.com/en-us/dotnet/api/system.net.ipaddress.getaddressbytes?view=net-8.0

**Comment by sklemer1** [comment]
The exception occured for IP `10.45.84.132/26`.

**Comment by rozmansi** [comment]
Thanks for reporting this. The problem is sign bit 1 from 132 in 10.45.84.132. (calculation is done in network byte order, so
