### ISSUE TITLE
resume from suspend - modern standy issue

### ISSUE THREAD

**Issue by efef** [Amebis/eduVPN#248]
Modern laptops have something called "modern standby" (S0 mode)
It means the laptop stays active during sleep. This S0 mode is non compatible with openVPN tap-driver or Wintun driver. After windows suspend, it can take up to 2 minutes before openVPN is reconnected which is quite annoying for users.

seems openVPN was looking into S0 in respect to DCO: https://github.com/OpenVPN/ovpn-dco-win/issues/64

for Tap driver or Wintun there is no fix yet.

Some laptops can be forced with a registry setting from S0 mode into S3 mode, however latest laptops don't support in BIOS S3 anymore. reference: https://www.reddit.com/r/Dell/comments/h0r56s/getting_back_s3_sleep_and_disabling_modern/

We need to investigate a workaround/fix for our Wintun implementation.

Further reference:
-https://learn.microsoft.com/en-us/windows-hardware/design/device-experiences/modern-standby

**Comment by rozmansi** [comment]
We are moving to https://codeberg.org/eduVPN/windows/issues/248
Sorry for the inconvenience.
