### ISSUE TITLE
Authentification required on every start when not manually disconnected before shutdown since updating to 4.1

### ISSUE THREAD

**Issue by Lukas-UAUX** [Amebis/eduVPN#249]
Hi,

since we updated to 4.1 (from 3.7) a bunch of our users report that they have to log in every time (after boot) although the certificates are still valid. After testing a bit it seams that occurs only when the user does not disconnect manually before shutting down the system (which is quite funny because this version actually contains a fix to gracefully end the connection on shutdown ;-) )  - the problem is that on my device I can not trigger this behavior which makes this quite erratic.

I already tried enabling the debug log in the config which did not write anything...

Do you have an idea where I can start searching to find what triggers this issue?

**Comment by jwijenbergh** [comment]
Hi Lukas, thanks for reporting the issue. We were aware of the issue and are currently investigating the root cause. I currently cannot reproduce it but we are doing more testing. The Linux client issue you're talking about has been solved a while ago so that can't be the issue. Do you currently have issues with the linux client that have this behaviour?

**Comment by rozmansi** [comment]
I cannot reproduce it either.

I am sorry for the long content below, but we would really love to resolve this once and for all. Let me share some technical details, perhaps somebody could help us troubleshoot this.

1. OAuth tokens are stored in `%LOCALAPPDATA%\SURF\eduVPN.Client.exe_Url_wwi1keok15fix22y0mfxlyx0umnf1uw0\4.1.0.0\user.config` (the _wwi1keok15fix22y0mfxlyx0umnf1uw0_ part may vary on your PC). Maybe something cleans the user `AppData\Local` folder? This folder should not be a part of a roaming profile if anyone in the world is still using this, right?

2. OAuth tokens are encrypted with the user DPAPI private key. This means they are useless for other users and for the same user on another PC. Maybe something resets user key on the local machine?

3. OAuth tokens are saved to file: 5 seconds after last change; at client exit; at WM_ENDSESSION (shutdown/restart/sign out). So, the tokens should really be saved in `%LOCALAPPDATA%\SURF\eduVPN.Client.exe_Url_wwi1keok15fix22y0mfxlyx0umnf1uw0\4.1.0.0\user.config` unless user authenticated less than 5 seconds before the client process is killed.

4. Maybe affected PCs are using Windows Fast Startup™ feature (Control Panel→Hardware and Sound→Power Options→Change what power buttons do)? This basically turns shutdown into sign-off&hibernate. Maybe this changes something?

5. The log, users may access at Settings→View log, is VPN log only. OAuth and eduvpn-common (the backend that runs the client authorization) are not logged here.

6. eduvpn-common log is available in `%LOCALAPPDATA%\SURF\eduVPN.Client.exe_Url_wwi1keok15fix22y0mfxlyx0umnf1uw0\log` file. This is probably **the most important log we need to retrieve** from the computer where this issue actually repeats! This is not an eduvpn-common issue, but this log will help clarify, why eduvpn-common is not happy with OAuth token from the client and why it is triggering re-auth.

7. The eduVPN Windows client also has some built-in .NET trace logging not enabled by default. It can be enabled by manually editing `C:\Program Files\eduVPN\Core\eduVPN.Client.exe.config`. Requires a Notepad that is Run as Administrator. Uncomment the `<system.diagnostics>` section and set the log path somewhere user has write-access (e.g. `C:\Users\Joe\Desktop\eduVPN.Client.log`). This is the second most important log from the computer where this issue actually repeats I would love to see.

**Comment by rozmansi** [comment]
8. Is somebody overriding `user.config` file in a logon script to preconfigure client list of servers or some other settings? [Registry](https://github.com/Amebis/eduVPN/blob/master/doc/Customization.md) should be used instead.

**Comment by tichachm** [comment]
Hi, here is some info my log (%LOCALAPPDATA%\SURF\eduVPN.Client.exe_Url_wwi1keok15fix22y0mfxlyx0umnf1uw0\log).
I can reproduce the issue once a day in the morning. But it is working fine the rest of the day.

`2024/08/28 07:50:34 - Go - DEBUG - Access token is expired
2024/08/28 07:50:34 - Go - DEBUG - Got a refresh token error: tokens are invalid due to: got invalid_grant when refreshing the tokens
2024/08/28 07:50:34 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/08/28 07:50:34 - Go - DEBUG - saving state file
2024/08/28 07:50:34 - Go - DEBUG - i18n: initializing languages...
2024/08/28 07:50:49 - Go - DEBUG - Access token is expired
2024/08/28 07:50:49 - Go - DEBUG - Got a refresh token error: tokens are invalid due to: got invalid_grant when refreshing the tokens
2024/08/28 07:50:59 - Go - DEBUG - saving state file
2024/08/28 07:50:59 - Go - DEBUG - saving state file
2024/08/28 12:12:25 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
2024/08/28 12:12:25 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/08/28 12:12:25 - Go - DEBUG - Access token is expired
2024/08/28 12:12:25 - Go - DEBUG - saving state file
2024/08/28 12:14:17 - Go - DEBUG - saving state file
2024/08/28 16:07:20 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
2024/08/28 16:07:20 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/08/28 16:07:20 - Go - DEBUG - Access token is expired
2024/08/28 16:07:21 - Go - DEBUG - saving state file
2024/08/30 10:14:22 - Go - DEBUG - Access token is expired
2024/08/30 10:14:22 - Go - DEBUG - Got a refresh token error: tokens are invalid due to: got invalid_grant when refreshing the tokens
2024/08/30 10:14:22 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/08/30 10:14:22 - Go - DEBUG - saving state file
2024/08/30 10:14:22 - Go - DEBUG - i18n: initializing languages...
2024/08/30 10:53:44 - Go - DEBUG - Access token is expired`

**Comment by tichachm** [comment]
Hi @rozmansi ,
I did some additional tests, 
1. user.config is not deleted on startup or after that, I can see the file when the error occurs.
2. user.config is writen new on every system restart and application start, even if no new server connection is established (according to timestamp), is this ok?
3. Windows Fast Startup is disabled on all our pcs
4. the log shows "Got a refresh token error: tokens are invalid due to: got invalid_grant when refreshing the tokens" does this help to get some more information?
5. I will try to get some additional .NET logs.

Thanks

**Comment by rozmansi** [comment]
Thank you for your feedback. With your help, I managed to reproduce the problem.

Preparing the solution...

**Comment by rozmansi** [comment]
I have released [4.1.5](https://github.com/Amebis/eduVPN/releases/tag/4.1.5) today. This issue should now be fixed.

**Comment by tichachm** [comment]
Hi @rozmansi 
thanks for the new release, the issue seems to be fixed on my test device.
But I am getting another error:

`System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei eduVPN.ViewModels.VPN.OpenVPNSession.Run()
   bei eduVPN.ViewModels.VPN.Session.Execute()
   bei eduVPN.ViewModels.Pages.ConnectionPage.<>c__DisplayClass33_0.<ActivateSession>b__0()`'
   
This happens when application is starting at sign-in.
After klicking "back" arrow to the serverselection screen it works.

Here is the log:

`2024/09/06 07:39:49 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/06 07:39:50 - Go - DEBUG - Access token is expired
2024/09/06 07:39:50 - Go - DEBUG - saving state file
2024/09/06 07:39:50 - Go - DEBUG - saving state file
2024/09/06 07:39:50 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/06 07:39:50 - Go - DEBUG - i18n: initializing languages...
2024/09/06 07:39:50 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/06 07:39:50 - Go - DEBUG - saving state file
2024/09/06 07:40:08 - Go - DEBUG - saving state file
2024/09/06 07:41:29 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
2024/09/06 07:41:29 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/06 07:41:29 - Go - DEBUG - saving state file
2024/09/06 07:43:35 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/06 07:43:36 - Go - DEBUG - saving state file
2024/09/06 07:43:36 - Go - DEBUG - saving state file
2024/09/06 07:43:36 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/06 07:43:36 - Go - DEBUG - i18n: initializing languages...
2024/09/06 07:43:36 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/06 07:43:36 - Go - DEBUG - saving state file
2024/09/06 07:47:19 - Go - DEBUG - saving state file`

**Comment by rozmansi** [comment]
Thanks for reporting this.

I have reviewed the code carefully but the `eduVPN.ViewModels.VPN.OpenVPNSession.Run()` is huge, and I couldn't identify which line is causing the issue. According to your description, there must be some functionality (NT service) not started yet, when the eduVPN client is already launched and trying to connect. And I can't figure out which one. But, I did find one UaF and one deadlock issue when reviewing the code. 😳

The problem occurs in the .NET part of the code, so the .NET tracelog would be most useful to me to get an idea where the problem strikes. Therefore, I have added some extra tracelog output in the `eduVPN.ViewModels.VPN.OpenVPNSession.Run()` and released [4.1.6](https://github.com/Amebis/eduVPN/releases/tag/4.1.6). Can you please install it and do this:

> 7. The eduVPN Windows client also has some built-in .NET trace logging not enabled by default. It can be enabled by manually editing `C:\Program Files\eduVPN\Core\eduVPN.Client.exe.config`. Requires a Notepad that is Run as Administrator. Uncomment the `<system.diagnostics>` section and set the log path somewhere user has write-access (e.g. `C:\Users\Joe\Desktop\eduVPN.Client.log`).

If you can reproduce the issue and deliver me this log, that should shed me some light what eduVPN client is missing early on boot.

You are really super helpful for me fixing this real-world corner cases I fail to reproduce in my lab.

**Comment by tichachm** [comment]
Hi, thanks for the new Version. With 4.1.6 I do not see the error message but reconncting after a reboot is not working, too.
So there seems still to be a issue.
Here is the new Log output:
`2024/09/09 07:27:26 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/09 07:27:26 - Go - DEBUG - Access token is expired
2024/09/09 07:27:26 - Go - DEBUG - saving state file
2024/09/09 07:27:26 - Go - DEBUG - saving state file
2024/09/09 07:27:26 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/09 07:27:26 - Go - DEBUG - i18n: initializing languages...
2024/09/09 07:27:26 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/09 07:27:26 - Go - DEBUG - saving state file
2024/09/09 09:04:56 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/09 09:04:56 - Go - DEBUG - Access token is expired
2024/09/10 07:20:52 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/10 07:20:52 - Go - DEBUG - saving state file
2024/09/10 07:20:52 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/10 07:20:52 - Go - DEBUG - i18n: initializing languages...
2024/09/10 07:28:04 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/10 07:28:24 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/10 07:28:24 - Go - DEBUG - saving state file
2024/09/10 07:28:24 - Go - DEBUG - i18n: initializing languages...
2024/09/10 07:28:24 - Go - DEBUG - saving state file
2024/09/10 07:28:29 - Go - DEBUG - saving state file
2024/09/10 07:28:36 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
2024/09/10 07:28:36 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/10 07:28:36 - Go - DEBUG - saving state file
2024/09/10 07:29:39 - Go - DEBUG - got 304 for discovery, server_list.json not modified
2024/09/10 07:29:39 - Go - DEBUG - saving state file
2024/09/10 07:29:39 - Go - DEBUG - saving state file
2024/09/10 07:29:39 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
2024/09/10 07:29:39 - Go - DEBUG - i18n: initializing languages...
2024/09/10 07:29:40 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/10 07:29:40 - Go - DEBUG - saving state file
2024/09/10 07:30:05 - Go - DEBUG - saving state file
2024/09/10 07:30:12 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
2024/09/10 07:30:12 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
2024/09/10 07:30:12 - Go - DEBUG - saving state file`

and the .NET trace:
`eduVPN.Client.exe Information: 0 : User session is ending
    DateTime=2024-09-10T05:28:36.4158221Z
eduVPN.Client.exe Information: 0 : OpenVPN monitor finished
    DateTime=2024-09-10T05:28:36.4473514Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnecting
    DateTime=2024-09-10T05:28:36.4473514Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnected
    DateTime=2024-09-10T05:28:36.4620001Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:28:36 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
    DateTime=2024-09-10T05:28:36.4633716Z
eduVPN.Client.exe Information: 0 : Tunnel cleanup
    DateTime=2024-09-10T05:28:36.4638769Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:28:36.4638769Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:28:36 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
    DateTime=2024-09-10T05:28:36.4647081Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:28:36 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:28:36.6264284Z
eduVPN.Client.exe Information: 0 : Saving user settings on window close
    DateTime=2024-09-10T05:28:36.6338339Z
eduVPN.Client.exe Information: 0 : Registering eduvpn-common engine
    DateTime=2024-09-10T05:29:38.7020797Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Main
    DateTime=2024-09-10T05:29:39.0309256Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GettingConfig
    DateTime=2024-09-10T05:29:39.2690537Z
eduVPN.Client.exe Information: 0 : Adding preconfigured Institute Access/Own servers https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:29:39.2866376Z
eduVPN.Client.exe Information: 0 : Getting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:29:39.4263350Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 - Go - DEBUG - got 304 for discovery, server_list.json not modified
    DateTime=2024-09-10T05:29:39.4380512Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:29:39.5209917Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:29:39.7889922Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GotConfig
    DateTime=2024-09-10T05:29:39.7943504Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:29:39.7970238Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 - Go - DEBUG - i18n: could not load printer with tag: 'en' from map
    DateTime=2024-09-10T05:29:39.8178468Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 - Go - DEBUG - i18n: initializing languages...
    DateTime=2024-09-10T05:29:39.8178468Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Main
    DateTime=2024-09-10T05:29:39.8194639Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Starting session monitor
    DateTime=2024-09-10T05:29:39.8782293Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Creating session monitor notification window
    DateTime=2024-09-10T05:29:39.8787330Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Enumerating existing sessions
    DateTime=2024-09-10T05:29:39.8795323Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Session: {ExecEnvId:0 State:4 SessionId:0 SessionName:Services HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Ignoring system/own session
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Session: {ExecEnvId:1 State:1 SessionId:1 SessionName:Console HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Ignoring system/own session
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Session: {ExecEnvId:2 State:0 SessionId:2 SessionName:31C5CE94259D4006A9E4#0 HostName: UserName:**** DomainName:**** FarmName:}
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:39 Ignoring system/own session
    DateTime=2024-09-10T05:29:39.8802440Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Connecting
    DateTime=2024-09-10T05:29:39.8909240Z
eduVPN.Client.exe Information: 0 : Starting OpenVPN management interface on 127.0.0.1
    DateTime=2024-09-10T05:29:39.9824410Z
eduVPN.Client.exe Information: 0 : Preparing OpenVPN configuration
    DateTime=2024-09-10T05:29:39.9929467Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnecting
    DateTime=2024-09-10T05:29:40.0036090Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnected
    DateTime=2024-09-10T05:29:40.0036090Z
eduVPN.Client.exe Information: 0 : Tunnel cleanup
    DateTime=2024-09-10T05:29:40.0036090Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:40 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
    DateTime=2024-09-10T05:29:40.0036090Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:29:40.0036090Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:40 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:29:40.0814905Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:29:40 Closing session monitor
    DateTime=2024-09-10T05:29:40.0879383Z
eduVPN.Client.exe Error: 0 : System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei eduVPN.ViewModels.VPN.OpenVPNSession.Run()
   bei eduVPN.ViewModels.VPN.Session.Execute()
   bei eduVPN.ViewModels.Pages.ConnectionPage.<>c__DisplayClass33_0.<ActivateSession>b__0()
    DateTime=2024-09-10T05:29:40.1071532Z
eduVPN.Client.exe Information: 0 : Saving user settings after change
    DateTime=2024-09-10T05:29:45.0935321Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GettingConfig
    DateTime=2024-09-10T05:30:00.6038524Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:30:00.6038524Z
eduVPN.Client.exe Information: 0 : eduvpn-common state AskProfile
    DateTime=2024-09-10T05:30:00.7372477Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GettingConfig
    DateTime=2024-09-10T05:30:05.3137380Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:30:05.4604632Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GotConfig
    DateTime=2024-09-10T05:30:05.4674107Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Starting session monitor
    DateTime=2024-09-10T05:30:05.4960947Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Creating session monitor notification window
    DateTime=2024-09-10T05:30:05.4960947Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Enumerating existing sessions
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Session: {ExecEnvId:0 State:4 SessionId:0 SessionName:Services HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Ignoring system/own session
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Session: {ExecEnvId:1 State:1 SessionId:1 SessionName:Console HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Ignoring system/own session
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Session: {ExecEnvId:2 State:0 SessionId:2 SessionName:31C5CE94259D4006A9E4#0 HostName: UserName:***** DomainName:***** FarmName:}
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:05 Ignoring system/own session
    DateTime=2024-09-10T05:30:05.4966064Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Connecting
    DateTime=2024-09-10T05:30:05.5006176Z
eduVPN.Client.exe Information: 0 : Starting OpenVPN management interface on 127.0.0.1
    DateTime=2024-09-10T05:30:05.5136410Z
eduVPN.Client.exe Information: 0 : Preparing OpenVPN configuration
    DateTime=2024-09-10T05:30:05.5136410Z
eduVPN.Client.exe Information: 0 : Connecting to OpenVPN interactive service
    DateTime=2024-09-10T05:30:05.5136410Z
eduVPN.Client.exe Information: 0 : Triggering openvpn.exe launch
    DateTime=2024-09-10T05:30:05.5231671Z
eduVPN.Client.exe Information: 0 : Waiting for openvpn.exe process
    DateTime=2024-09-10T05:30:05.6389081Z
eduVPN.Client.exe Information: 0 : Starting OpenVPN management session
    DateTime=2024-09-10T05:30:05.6700745Z
eduVPN.Client.exe Information: 0 : OpenVPN monitor started
    DateTime=2024-09-10T05:30:05.6816415Z
eduVPN.Client.exe Information: 0 : OpenVPN ready
    DateTime=2024-09-10T05:30:05.6816415Z
eduVPN.Client.exe Information: 0 : Releasing OpenVPN
    DateTime=2024-09-10T05:30:05.7935342Z
eduVPN.Client.exe Information: 0 : OpenVPN connected
    DateTime=2024-09-10T05:30:05.8259230Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Connected
    DateTime=2024-09-10T05:30:05.8259230Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946205,TCP_CONNECT,,,,,,
    DateTime=2024-09-10T05:30:05.8725892Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946205,WAIT,,,,,,
    DateTime=2024-09-10T05:30:05.8725892Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946205,AUTH,,,,,,
    DateTime=2024-09-10T05:30:05.9040118Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946206,GET_CONFIG,,,,,,
    DateTime=2024-09-10T05:30:06.8914546Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946206,ASSIGN_IP,,10.37.43.10,,,,,fd03::1:10a
    DateTime=2024-09-10T05:30:06.9072337Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946206,ADD_ROUTES,,,,,,
    DateTime=2024-09-10T05:30:06.9072337Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946206,CONNECTED,SUCCESS,10.37.43.10,137.250.27.123,443,172.27.64.74,49953,fd03::1:10a
    DateTime=2024-09-10T05:30:06.9072337Z
eduVPN.Client.exe Information: 0 : Saving user settings after change
    DateTime=2024-09-10T05:30:08.0565992Z
eduVPN.Client.exe Information: 0 : Saving user settings after change
    DateTime=2024-09-10T05:30:10.5064265Z
eduVPN.Client.exe Information: 0 : OpenVPN monitor finished
    DateTime=2024-09-10T05:30:12.2516121Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnecting
    DateTime=2024-09-10T05:30:12.2524997Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Disconnected
    DateTime=2024-09-10T05:30:12.3744025Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:12 - Go - DEBUG - attempt an invalid self-transition: Disconnecting
    DateTime=2024-09-10T05:30:12.3744025Z
eduVPN.Client.exe Information: 0 : Tunnel cleanup
    DateTime=2024-09-10T05:30:12.3749074Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:30:12.3749074Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:12 - Go - DEBUG - ProxyGuard cancel gave an error: no ProxyGuard cancel function
    DateTime=2024-09-10T05:30:12.3755420Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:12 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:30:12.5297744Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:12 Closing session monitor
    DateTime=2024-09-10T05:30:12.5391592Z
eduVPN.Client.exe Information: 0 : Saving user settings after change
    DateTime=2024-09-10T05:30:17.3815759Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:46 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:30:46.9046252Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GettingConfig
    DateTime=2024-09-10T05:30:46.9198075Z
eduVPN.Client.exe Information: 0 : Setting OAuth token for https://eduvpn.rz.uni-augsburg.de/
    DateTime=2024-09-10T05:30:46.9213651Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 - Go - DEBUG - saving state file
    DateTime=2024-09-10T05:30:47.1412948Z
eduVPN.Client.exe Information: 0 : eduvpn-common state GotConfig
    DateTime=2024-09-10T05:30:47.1465720Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Starting session monitor
    DateTime=2024-09-10T05:30:47.1648081Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Creating session monitor notification window
    DateTime=2024-09-10T05:30:47.1653123Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Enumerating existing sessions
    DateTime=2024-09-10T05:30:47.1658369Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Session: {ExecEnvId:0 State:4 SessionId:0 SessionName:Services HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Ignoring system/own session
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Session: {ExecEnvId:1 State:1 SessionId:1 SessionName:Console HostName: UserName: DomainName: FarmName:}
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Ignoring system/own session
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Session: {ExecEnvId:2 State:0 SessionId:2 SessionName:31C5CE94259D4006A9E4#0 HostName: UserName:******* DomainName:******* FarmName:}
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : 2024/09/10 07:30:47 Ignoring system/own session
    DateTime=2024-09-10T05:30:47.1664771Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Connecting
    DateTime=2024-09-10T05:30:47.1691982Z
eduVPN.Client.exe Information: 0 : Starting OpenVPN management interface on 127.0.0.1
    DateTime=2024-09-10T05:30:47.1838366Z
eduVPN.Client.exe Information: 0 : Preparing OpenVPN configuration
    DateTime=2024-09-10T05:30:47.1838366Z
eduVPN.Client.exe Information: 0 : Connecting to OpenVPN interactive service
    DateTime=2024-09-10T05:30:47.1838366Z
eduVPN.Client.exe Information: 0 : Triggering openvpn.exe launch
    DateTime=2024-09-10T05:30:47.1838366Z
eduVPN.Client.exe Information: 0 : Waiting for openvpn.exe process
    DateTime=2024-09-10T05:30:47.1878985Z
eduVPN.Client.exe Information: 0 : Starting OpenVPN management session
    DateTime=2024-09-10T05:30:47.2093581Z
eduVPN.Client.exe Information: 0 : OpenVPN monitor started
    DateTime=2024-09-10T05:30:47.2093581Z
eduVPN.Client.exe Information: 0 : OpenVPN ready
    DateTime=2024-09-10T05:30:47.2093581Z
eduVPN.Client.exe Information: 0 : Releasing OpenVPN
    DateTime=2024-09-10T05:30:47.3247460Z
eduVPN.Client.exe Information: 0 : OpenVPN connected
    DateTime=2024-09-10T05:30:47.3305112Z
eduVPN.Client.exe Information: 0 : eduvpn-common state Connected
    DateTime=2024-09-10T05:30:47.3305112Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,TCP_CONNECT,,,,,,
    DateTime=2024-09-10T05:30:47.3693169Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,WAIT,,,,,,
    DateTime=2024-09-10T05:30:47.3703351Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,AUTH,,,,,,
    DateTime=2024-09-10T05:30:47.4051518Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,ASSIGN_IP,,10.37.146.145,,,,,fd02:1::1:11
    DateTime=2024-09-10T05:30:48.1678396Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,ADD_ROUTES,,,,,,
    DateTime=2024-09-10T05:30:48.1688402Z
eduVPN.Client.exe Information: 0 : OpenVPN state: 1725946248,CONNECTED,SUCCESS,10.37.146.145,137.250.27.106,443,172.27.64.74,50234,fd02:1::1:11
    DateTime=2024-09-10T05:30:48.1708501Z
eduVPN.Client.exe Information: 0 : Saving user settings after change
    DateTime=2024-09-10T05:30:52.1806526Z
`

**Comment by rozmansi** [comment]
> Hi, thanks for the new Version. With 4.1.6 I do not see the error message but reconncting after a reboot is not working, too. So there seems still to be a issue.

That was expected. I haven't identified your problem yet and didn't fix it yet. Just added more tracelogging to better locate the place where it breaks.

**Comment by rozmansi** [comment]
A new day, a new release: [4.1.7](https://github.com/Amebis/eduVPN/releases/tag/4.1.7)

I believe I have found and fixed your auto-reconnect bug. I could reproduce your issue by preconfiguring a server in the registry and then letting client to auto-reconnect by restarting it without disconnecting first. It works now.

Thank you for your patience and support. ❤️

**Comment by tichachm** [comment]
Thanks for the Update, working fine on my device.
