### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by jwijenbergh** [Amebis/eduVPN#252]
Reported at: https://github.com/eduvpn/python-eduvpn-client/issues/610#issue-2637230670

I'm not sure this is a windows client issue or a server/network issue, but I am posting it here as this is the right place for windows client reports

----

Hello Support,

many of our users are complaining that they can connect via VPN but can't do anything (surf, access our service etc.). It seems that the traffic is blocked, but when you reconnect it works again. The error occurs every 2 days and you have to reconnect 5-20 times to get it working again.
Sometimes it also connects, but has no connection, this is only shown by the fact that it stops at 1.5kB when downloading and 50kB when uploading.

Error message:

System.Exception: Failed to obtain a VPN configuration for server: 'https://eduvpn.xx-xxx.de/'. The cause of the error is: Timeout reached contacting URL: 'https://eduvpn.xx-xxx.de/vpn-user-portal/api/v3/info'.with eduVPN.Engine.GetConfig(Cookie cookie, ServerType type, String id, Boolean tcp, Boolean startup)
with eduVPN.ViewModels.Windows.ConnectWizard.<>c__DisplayClass69_0.b__0()
for System.Threading.Tasks.Task`1.InnerInvoke()
for System.Threading.Tasks.Task.Execute()
--- End of stack monitoring from the previous location where the exception was raised ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
with System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
for eduVPN.ViewModels.Windows.ConnectWizard.d__69.MoveNext()
--- End of batch monitoring from the previous location where the exception was raised ---
for System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
with System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
with System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

THX

cc @Network-Joe

**Comment by jwijenbergh** [comment]
@Network-Joe

Thanks for the issue report, I have moved it here as this is a better place.

some additional questions:
- Which server is this exactly?
- Are these clients "managed devices"?
- Does this always happen on the same network?
- Are you the server operator/admin or a user?

I think it's best if you e-mail us with as much details as possible at eduvpn-support@lists.geant.org

**Comment by rozmansi** [comment]
According to the error trace, this computer has had connectivity issues to the https://eduvpn.xx-xxx.de/ URL before it even attempted to establish a VPN connection.

**Comment by jwijenbergh** [comment]
@Network-Joe let us know if still an issue. We have not received an e-mail yet
