### ISSUE TITLE
Rethink how to show providers/profiles

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#28]
Hi,

I'd like to just add this here for future reference. Maybe what we have at the moment is good enough, or even better than what I propose below :)

In the current application it is not possible to "discover" new profiles available to the user. The user would have to click "add new profile", choose the provider and then the profile. If the list of profiles changes, e.g. one is added or deleted, this is unknown to the user. To be clear, this applies foremost to "Institute Access".

Current scenario: all profiles (bound to provider) are shown on the home screen. To add a profile the user has to choose the provider again and then select the profile.

As a improvement I could see two approaches:

1. Show only the provider(s) on the "home" screen. A second screen with "Choose profile" would be shown after choosing a provider with an up to date list of available profiles, and after choosing a profile (previously chosen on top if any) the user will be connected (extra screen can be skipped if there is only 1 profile);
2. Show all available profiles from all available providers on the "home" screen.

## 1
The advantages of this scenario is that the follow the current API design. It doesn't require a bunch of API calls to show the home screen. It is cleaner to only start performing calls when the user actually chose the provider. The "Add profile" button would become "Add provider".

The disadvantage is that there is an extra screen where the user chooses the profile (if there is more than 1 available) every time instead of just at the "Add profile" stage. Maybe an "always use this" could be added somehow, not sure if that makes sense.

## 2
The advantage is that the current design can be retained, just the profile chooser after adding a provider will go away.

The disadvantage here is that this creates potentially a lot of visible profiles on the "home" screen, and requires lots of calls to all providers at start-up to query for available profiles and user information and possibly messages.

What do you guys think?

**Comment by rozmansi** [comment]
Ad. 1: "always use this" voids your initial idea: newly available profiles will remain hidden to the user once he picks one to "alway use it". Unless overridden to re-display the full list of profiles each time there are any new profiles available.

I suggest you put this discussion in perspective asking the following questions:
1. How many distinct providers will the typical user have access to?
2. How many distinct profiles will the typical user have access to?
3. How often will providers add new profiles? Will they do some promotional campaign to notify users of new services, allowing them to _piggy-back_ a user notice to set up a new profile in the eduVPN client?

If the numbers in 1. and 2. are low we can display all providers-profiles combinations as a flat list on the home screen. Please, keep in mind we are not typical end users. We are running unusual amount of "providers" and "profiles" while testing the eduVPN client. A typical end-user might be totally fine with a flat list of all his available profiles, whether we pushed them or he added them one by one.

**Comment by rozmansi** [comment]
The client was extended to support various profile management modes that can now be configured using XML eduVPN.Client.exe.config file described [here](https://github.com/Amebis/eduVPN/blob/master/doc/ConnectingProfileSelectMode.md).

Please, take a look at each available mode and let me know which one to set as default.

**Comment by fkooman** [comment]
I vote for 1 with the optimization that the user doesn't need to choose if there's only one profile. I guess we may have to revisit this in the future though... Not sure what the 'normal' pattern of use will be...

**Comment by fkooman** [comment]
Some more ideas:

With this flow we could even remove all network requests @ application start I guess, the connections only start when choosing a provider: `info.json`, possibly OAuth for refresh token, profile_list, profile_config, connect to VPN. 

The discovery files are only needed when adding a new instance, or maybe periodically to update logos and names in the app...

(I'm focusing so much on "optimizing" this as I expect most users will be running Windows, and thus this app is the most important...)

**Comment by efef** [comment]
for user experience I would appreciate that a new user, just installing eduVPN, would quicker connect the VPN. I would propose that when using "secure internet", after successful login the user would automatically connect to the FIRST profile (usually there is only one). Now there is a step in between which isn't necessarily to my opinion. This quicker connect function shouldn't work for "institute access"

**Comment by fkooman** [comment]
#135
