### ISSUE TITLE
[discuss] desktop icon

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#31]
It seems nice to add an eduVPN desktop icon on installation. What do you guys think? 

@sveeke @efef @mkoelewijn

**Comment by rozmansi** [comment]
I have the code for desktop shortcut creation ready but commented. Just decide and let me know.

**Comment by rozmansi** [comment]
Right! I personally hate when software clutters my desktop. Other users find it convenient to keep everything on their Desktops. There's no one-rule-to-fit-them-all here.

I like the "[X] Create desktop icon" checkbox suggestion. Let's implement it.
