### ISSUE TITLE
allow configuring discovery URLs (in config file?)

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#32]
I can't test the "secure internet" flow now as I don't have access to any of the production instances

**Comment by rozmansi** [comment]
This is already taken care of.

Please download the [master configuration XML](https://github.com/Amebis/eduVPN/files/1459486/eduVPN.Client.exe.zip), modify it to your needs, then overwrite the one installed by the client at C:\Program Files\eduVPN.

The `<applicationSettings>` defines the all-users application settings. The `<userSettings>` define user defaults.

Your ideas to make other aspects of the client configurable are welcome.
