### ISSUE TITLE
Auto-updating

### ISSUE THREAD

**Issue by rozmansi** [Amebis/eduVPN#38]

**Comment by fkooman** [comment]
https://static.eduvpn.nl/auto-update/windows/x64.json (https://static.eduvpn.nl/auto-update/windows/x64.json.sig)
https://static.eduvpn.nl/auto-update/windows/x86.json (https://static.eduvpn.nl/auto-update/windows/x86.json.sig)

**Comment by fkooman** [comment]
public key for "auto update" signing: `15nh06ilJd5f9hbH5rWGgU+qw9IxBHE+j2wVKshidkA=`
