### ISSUE TITLE
Can't add Institute access profiles

### ISSUE THREAD

**Issue by mkoelewijn** [Amebis/eduVPN#41]
(this is about the default installation)

First off all i added the Internet access profile which works fine. However when i try to add a "institute access" profile afterwords (tried 2 different institutions) i only can choose the same profile i am connected to; "Amsterdam" (i should get to choose a profile that is called 'NW-testbed")

<img width="312" alt="screen shot 2017-11-22 at 16 00 47" src="https://user-images.githubusercontent.com/26085443/33133890-7b974c62-cf9e-11e7-8702-1a12ae8d785d.png">

<img width="312" alt="screen shot 2017-11-22 at 16 01 27" src="https://user-images.githubusercontent.com/26085443/33133891-7bb0c57a-cf9e-11e7-8b55-0a323ea4a4d6.png">

**Comment by mkoelewijn** [comment]
hmmm, after i restart the client i do see the proper profiles now...

**Comment by rozmansi** [comment]
Thank you for reporting this. I admit I haven't tested the secure internet for a while now.
