### ISSUE TITLE
clicking other provider on home screen while connected has no effect

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#43]
this kinda makes sense, but is confusing. The user has to disconnect first manually from the connected provider and then click on the other one to connect. 

Maybe a dialog could be shown asking to disconnect from the old one.

Default configuration file 1.0.12, Windows 7.

**Comment by rozmansi** [comment]
Which mode are you using?

**Comment by rozmansi** [comment]
I looked into this and I am confirming this is indeed a bug - this once worked as expected, but got broken with the introduction of "modes".
