### ISSUE TITLE
deleting provider/profile does not remove access_token/refresh_token

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#44]
After deleting a provider/profile from the main screen the associated access_token (and maybe certificate(s)?) are not removed.

expected: tokens and certificates removed.

**Comment by rozmansi** [comment]
I'd say the other way around: delete certificates (and maybe associated access_tokens).

Certificates could be cleaned with no harm - they are reloaded on demand, should the user choose to connect to the removed instance again later.

However, the client keeps the access tokens on purpose. Mainly simplicity. But there is still some rationale beyond simplicity alone.

The instance/profile forget feature just removes entries from the _previously connected_ list. It is not the same as removing the client-instance established trust. Imagine user removing a bookmark from a web browser and the browser would remove all stored passwords and certificates for that page too.

Access tokens are reused between all instances sharing the same OAuth authorization endpoint URI. The same instance can occur on Secure Internet and Institute Access lists. Removing access tokens should be careful to remove them only after there are no more associated instances left.

The access tokens are reused and kept in a client dictionary. So the storage is not a concern.

**Comment by fkooman** [comment]
It is just very confusing regarding UX that a removal is not really a removal, no matter how it is called.

I agree with you for the "Secure Internet" case, removing one entry does not remove the OAuth token as it is also valid at the other instances/providers. There you'd remove the access token when the last entry is removed.

For "Institute Access" all providers have their own OAuth endpoint (by definition) and thus everything can be deleted on "forget/remove" in the UI.
