### ISSUE TITLE
what to do when user is not enrolled for 2FA?

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#45]
Whenever a profile is available, but the user is not enrolled for 2FA they will be unable to connect.  I think we talked about this before, but maybe it was forgotten, or I don't know... @mkoelewijn also mentioned this issue recently. 

Situation: normal users will NOT see the VPN (user) portal at all, they will only use the Windows app.

I see a number of possible solutions for this:

1. I don't even list the profiles that require 2FA through the API;
2. The eduVPN app shows a message that 2FA enrollment is required and opens the browser to the "enroll" page (would require discovery through `info.json` I guess for the exact URL!);
3. The eduVPN app shows a message that 2FA enrollment is required through the "portal" and sends the browser of to the `base_uri` of the provider, typically opening the user portal;
4. We embed 2FA enrollment in the app.

The first one would be the easiest, but would be confusing to users... they would never know! 

The second one is the nicest I guess, but requires changes to the `info.json` file, not a big deal actually... it won't break anything.

The third is the easiest way and requires no work from me ;-) 

The fourth is unreasonable at this time.

I guess option 2 is the best. What do you think?

**Comment by mkoelewijn** [comment]
Option 2 would be great!

**Comment by rozmansi** [comment]
Fine with me. François, please add the URI to `info.json` and I shall do the rest.

**Comment by fkooman** [comment]
Done: https://github.com/eduvpn/documentation/blob/master/API.md#api-discovery
