### ISSUE TITLE
Additional code-signing certificate check for self-updates

### ISSUE THREAD

**Issue by rozmansi** [Amebis/eduVPN#47]
Introduce additional check of code-signing signature _and_ certificate of downloaded self-update executable.

This will require an intermediate update to:
- change self-updating code to:
   - switch to a new self-update discovery URI (e.g. `/auto-update/windows2020.json`)
   - accept the new code-signing certificate
- code-signed with current certificate

This needs to be done _before_ the current certificate expires and _after_ the new code-signing certificate is acquired.

Discuss certificate rollover strategy with @fkooman.

**Comment by fkooman** [comment]
Hmm... maybe this gets too complicated? What do you think?

**Comment by rozmansi** [comment]
I agree. We have this JSON signing & SHA-256 verification implemented and I think self-updating is safe enough for now.

I propose we close this for now but stay alert should there be any new good idea how to additionally fortify it.
