### ISSUE TITLE
OAuth client ID

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#51]
The current `client_id` is `org.eduvpn.app`. Please start using `org.eduvpn.app.windows`. Everything else related to OAuth stays the same.

**Comment by rozmansi** [comment]
Addressed in 492c829c5bcef7c6bea0e3d4a2f20f5d4ad192cc.

**Comment by fkooman** [comment]
Right, I was just adding issues at all clients, wasn't sure about the status here :) Thanks! Should work everywhere now!
