### ISSUE TITLE
do not force reboot on upgrade

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#61]
if a reboot is required, ask the user.

**Comment by rozmansi** [comment]
I was able to reproduce the problem in VM. The `/passive` WiX bundle installer flag makes the difference. This flag instructs installer not only to skip unneeded annoying "Install" and "Close" button clicking, but also skips prompting the user to reboot if required -- WiX takes the `/passive` "don't ask questions" flag too seriously.

Therefore, I suggest you remove the `/passive` flag from `arguments` in `windows.json`. The user will need to make two extra clicks while updating, but _will_ be given a choice should reboot be required.

Other than that, I fail to see a reason why this reboot was required in the first place. The self-updater closes the client before launching an update, the `eduVPNOpenVPN.msi` stops the `openvpnserv.exe` service before updating... I keep thinking what else could be write-locked.

**Comment by fkooman** [comment]
I removed the `/passive` flag now. Let's hope that solves it. Thanks!
