### ISSUE TITLE
documentation for SCCM deployment

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#64]
How would one go about using SCCM to deploy eduVPN for Windows? Using the MSIs? How to deal with disabling auto update and allowing the system admins to decide when to push an update?

**Comment by fkooman** [comment]
By the way, it doesn't need to be extensive, we can assume people who want to do this are familiar with SCCM.

**Comment by rozmansi** [comment]
In 4d6025cc8ec478477af85653963f1b1cb59465fc, I have elaborated the eduVPN Client for Windows deployment [here](https://github.com/Amebis/eduVPN/blob/master/doc/Deployment.md).

Should IT admins require more insight into the eduVPN Client, or more options to deploy and configure it, please let me know.

Upgrading eduVPN Client to support GPO provisioning with ADM administrative templates over the `eduVPN.Client.exe.config` file might be the next feature IT admins will ask for.
