### ISSUE TITLE
buffer size on Windows 7

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#65]
It seems de default buffer size on Windows 7 is 8912, you can see that in the log of OpenVPN when it connects.

Windows 7:
`Fri Dec 22 23:37:50 2017 Socket Buffers: R=[8192->8192] S=[8192->8192]`

Windows 10:
`Fri Dec 22 23:36:18 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]`

On Windows 7 this seems way too low to get any decent (download) performance. See e.g. https://community.openvpn.net/openvpn/ticket/640

I see 3 possible approaches:

- fix this in OpenVPN (as per ticket)
- make the server push higher buffer sizes to all clients (not ideal, as this is only needed for Windows 7)
- modify the eduVPN client to add buffer "overrides" on Windows 7 specifically

Just to make sure, I talk about these configuration options:

```
       --sndbuf size
              Set the TCP/UDP socket send buffer size.  Defaults to  operation
              system default.

       --rcvbuf size
              Set  the TCP/UDP socket receive buffer size.  Defaults to opera‐
              tion system default.
```

**Comment by rozmansi** [comment]
If you have time to read thru another discussion about buffer sizes at https://community.openvpn.net/openvpn/ticket/461, you will notice, that OpenVPN team prefers to leave the default buffer size decision to OS or the end-user.

Therefore, I agree we _fix_ this for Windows 7 only. On the client side of course.
