### ISSUE TITLE
Version does not match actual version in list of installed software

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#67]

**Comment by rozmansi** [comment]
1. The version displayed on the About dialogue is the version of the `eduVPN.dll` assembly. The `eduVPN.dll` is the heart of the eduVPN Client for Windows. The version of the `eduVPN.Client.exe` assembly should also match it.
    Unfortunately, .NET assembly versions are always four-component. I have modified the code in f553d04ec3ab97571c8bcc503ae3802ee02189da to truncate trailing _.0_ in version number before displaying.

2. The version reported in the _Programs and Features_ dialogue (or _Apps & Features_) is the version of WiX EXE installer bundle. 1. and 2. are logically not the same version.
   When we update the `eduVPNCore.msi` - which contains the `eduVPN.dll` and shares its version - to 1.0.16 we also version the EXE bundle to 1.0.16.
   When we update the `eduVPNOpenVPN.msi` - e.g. when OpenVPN 2.4.5 is published - we need to increment EXE bundle version again, let's say to 1.0.16.1, but keeping the 1.0.16 of the `eduVPNCore.msi` - providing it didn't change at all.
   Therefore, sometimes you will notice the slight version discrepancy.
