### ISSUE TITLE
upgrade to OpenVPN 2.4.5

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#78]

**Comment by rozmansi** [comment]
Finally. It will take me a day or two to modify the build process and test everything. The 2.4.5 contains my patch allowing multiple OpenVPN interactive service instances out-of-the-box. This means we no longer need to compile my patched version and can reuse stock _openvpnserv.exe_ simplifying build process.

**Comment by rozmansi** [comment]
Done. Commit c6ced0ba4db68c062963f7c2e33f78bc6db92085.
