### ISSUE TITLE
simplify updater notification

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#88]
Proposed mockup:

![image](https://user-images.githubusercontent.com/616885/38388718-4df18da8-391c-11e8-8c24-bd3fa459dab1.png)

**Comment by rozmansi** [comment]
This requires two things:

1. Introduce a simple change log text to the `windows.json` discovery file. Easy.
2. Implementation of a custom collapsible control extending the pop-up windows to support dynamic resizing. This might take like an hour or a week of work. I shall give it a try and see if it's doable in with a reasonable effort.

**Comment by fkooman** [comment]
Maybe we can simplify it even more. Only have the button and the window title. And maybe a link to the changelog. I'll make a new mockup soon.

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/38448154-8ada4502-3a02-11e8-92a6-028435cadcd5.png)

**Comment by fkooman** [comment]
So basically what you had was good! Maybe get rid of the version number information... It is not that important for users, and they'll see it when they click "What's New?"

**Comment by fkooman** [comment]
"Client will restart" -> "Application will restart"

**Comment by fkooman** [comment]
(This mockup was not mine, and now that I think more about it, it only makes things more confusing and inconsistent).

I do think we maybe should move from "eduVPN Client" to just "eduVPN".

**Comment by rozmansi** [comment]
> I do think we maybe should move naming consistently from "eduVPN Client" to just "eduVPN".

I was meticulous throughout the GUI to refer the client as the "eduVPN Client", and not using a general term "eduVPN", to distinguish the VPN client software and the eduVPN ecosystem. Imagine true meaning of the prompts like "Upgrade eduVPN", "Close eduVPN", "Remove eduVPN"... :)

So, there's a reason for "eduVPN Client".

Taking all this into consideration, I propose:

- Start Menu shortcut, main window title, and Add/Remove Programs entry to remain "eduVPN Client" ("...for Windows" is redundant here). This exactly expresses what user is going to launch, is working with or going to uninstall.

- "eduVPN Client" in the client GUI becomes just "client". I agree: constantly using "eduVPN Client" within the client dialogues and prompts is excessive and it makes texts bloated.

**Comment by rozmansi** [comment]
Me trying to be over-explainative in GUI texts reminds me of a joke:

>German for the beginners
>
>As most of you know German is pretty easy. The person who knows a bit of latin and tenses is used to koniugazion, and memorizes it without any problems. This is, after all, what claim most of the teachers after the very first lesson. Then all the _der_, _des_, _den_, _dem_, _die_, starts and we hear that everything is logical so... it's easy.
>
>At the beggining we buy a beautiful class book, like those printed in Dortmund and tells us about customs of the Hottentotten tribe. The book says that cangaroos (_Beutelratten_) are chased and kept in cages (_Koffer_) with plait (_Lattengitter_) to keep an eye on them. The gases are called "cages from a plait" (_Lattengitterkoffer_) and if it contains a cangaroo it is called _Beutelrattenlattengitterkoffer_.
>
>Once upon a time, _Hottentotten_ stop a killer _Attentater_, who is thought to be a killer of his mother _Mutter_ from _Hottentotten_ (_Hottentottenmutter_), a mother of a fool (_Stottertrottel_. This mother in German is called: _Hottentottenstottertrottelmutter_ and her killer is called _Hottentottenstottertrottelmutterattentater_).
>
>The police catches the killer and puts him in a cangaroo cage (_Beutelrattenlattengitterkoffer_), but he escapes. So the searching starts. The knight from the tribe runs up to the leader and says:
>- I caught the killer! (_Attentatter_)
>- Yes? Which one? - the leader asks.
>- _Beutelrattenlattengitterkofferattentatter_ - replies the knight.
>- What?! The killer who is in a cage for cangaroos from the plait?
>- Yes sir. the _Hottentottenstottertrottelmutterattentater_ (killer of a hottentoten mother of a foolish son).
>- Ahhh yes, of course, naturlich! you should say it at the beginning that you caught _Hottentottenstottertrottelmutterbeutelrattenlattengitterkofferattentatter_!
