### ISSUE TITLE
dev instructions not complete

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#89]
![image](https://user-images.githubusercontent.com/616885/38812712-5fe05b42-418d-11e8-9052-599e47711a3d.png)

**Comment by rozmansi** [comment]
Ouch, I have removed the Windows 8.1 SDK from required Visual Studio feature set after switching to stock openvpnserv.exe binary. I forgot the eduEd25519 still requires it never the less. I shall put it back into documentation.

**Comment by fkooman** [comment]
Also: 
```
        "bin\wixcop.exe" -nologo "-set1C:\Users\F. Kooman\source\repos\eduVPN\wixcop.xml" "eduVPNTAPWinPre.wxs"
'bin\wixcop.exe' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: '"bin\wixcop.exe' : return code '0x1'
Stop.
```
