### ISSUE TITLE
block traffic outside VPN if/when VPN fails

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#91]
One nice (necessary?) feature would be to be able to block traffic outside the VPN when the VPN is (supposed) to be up. If the VPN fails, e.g. because WiFi dies and comes back 5 minutes later, it would be nice it won't allow any application to access the Internet outside the VPN...

Is this doable?

**Comment by rozmansi** [comment]
Probably.

However, we need to discuss some design choices first.

1. The blocking would be applicable on a per-profile basis: mostly to the Secure Internet use-case, but could also be required by selected profiles, so Let's Connect! can use the same blocking too. This means that each individual profile should specify whether it is supposed to be the default-and-only gateway or not.

2. The blocking could be implemented by setting lowest metric default gateway to 127.0.0.1 and ::1, and setting an appropriate static route to the eduVPN server to allow reestablishing the OpenVPN connection later.
   Another option is to use a firewall route to temporary block all traffic with an exception of OpenVPN.

   Anyway, we decide to implement that, we need to test the proper blocking method first. Perhaps we can borrow the knowledge about blocking out-of-VPN traffic from OpenVPN expertise.

3. Anything eduVPN client does to fiddle with network settings _will_ require elevation. This means we need to create a system service to perform this task on eduVPN client's behalf. This is quite an extension exceeding current maintenance plan for the eduVPN client. However, something we can nicely fit into the plan for v2.0.

**Comment by fkooman** [comment]
Initially I though this could be done as part of OpenVPN, like `--block-outside-dns`, but that won't be enough I guess as OpenVPN is not necessarily running (anymore). 

At least it has to work through suspend/hibernate cycles as to have no traffic go outside the VPN. Obviously "local" traffic to the DHCP / DNS server needs to be allowed still. 

I think this may indeed be quite complicated to get right in all scenarios.
