### ISSUE TITLE
Upgrade to OpenVPN 2.4.6

### ISSUE THREAD

**Issue by rozmansi** [Amebis/eduVPN#93]
Once the OpenVPN 2.4.6 is available, update the eduVPN & Let's Connect! clients to use it. Mind the new TAP/TUN driver version.

**Comment by fkooman** [comment]
I think this issue was resolved already, and it was 2.4.6 and not 2.5.6? :-)

**Comment by rozmansi** [comment]
Thank you, François! You're right. This was addressed in cac1ff88cd2b1be29497ce1a8f71c836bb5ed397.
