### ISSUE TITLE
No update button when upgrade got cancelled

### ISSUE THREAD

**Issue by sveeke** [Amebis/eduVPN#94]
A user cancelled the upgrade process, but's doesn't get a new notice to upgrade after restarting the app. Is this intended behaviour or a bug? He wants to update the app, but is unable to do so now from the app itself.

**Comment by rozmansi** [comment]
The user will be re-prompted after a day or two again. This delay is built-in intentionally: for a less intrusive user experience.

In urgent cases, the user can download the latest version of the client from the web and install it over the current one. This is exactly what an update process does - only in an automated way.
