### ISSUE TITLE
when disabling user in admin, client keeps obtaining new certificates

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#97]
1. Connect to VPN
2. Go to admin and disable the user
3. Client gets disconnected
4. Client loops by obtaining a new certificate every time, the connection obviously never succeeds.

When you manually client 'disconnect' and try to connect again you get the notification that the user is disabled. 

Maybe it is possible before obtaining a new certificate to check if the user is disabled? that would avoid the loop to obtain a certificate.

Is that reasonable?

**Comment by rozmansi** [comment]
The core of this issue is the openvpn.exe process returning `"auth-failure"` for both cases: invalid or expired client certificate, and user disabled.

Thank you for pointing this out. I totally forgot about the later case.

**Comment by rozmansi** [comment]
A welcome side effect of this patch is that the user info is now refreshed on `"auth-failure"`, refreshing the status page with a "You have been disabled!" warning notice.
