### ISSUE TITLE
Enter URL of your provider shown instead of added profiles

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#98]
Observed behavior:

1. Add two profiles from 2 different VPN servers;
2. Close the client;
3. Make it impossible to access one of the profiles (e.g. the user is removed from the ACL, so is no longer entitled to use the profile)
4. Start the client.
5. "Enter URL of your Provider" is shown instead of the other profile from the other server that is still valid. It is not possible to go the list of profiles from the point. One has to enter a URL first before it works.

Expected behavior:

The "valid" profile that is still available should be shown instead of the "Enter URL of your provider", and maybe a warning that one of the configured profiles is no longer available for use?

Note: this is a problem with this "flow", if we would only list the configured servers and after choosing a server, list the (still) available profiles this problem would not occur like this...

**Comment by rozmansi** [comment]
Thanks. I shall look into it.
