### ISSUE TITLE
Unable to delete provider that no longer has accessible profiles

### ISSUE THREAD

**Issue by fkooman** [Amebis/eduVPN#99]
Related to #98.

If you have only 1 profile configured for a particular server and it is no longer available to you, the access token/refresh_token is retained. This is actually expected as long as it is valid, but if you try to add the profile again by entering the URL, the "old" token is used.

It would probably be better to show the profile that was once added and is no longer available in a "no longer available" state so you can at least "forget" it manually by right clicking it. Trying to add it again will then trigger the authorization flow again (if I am not mistaken) instead of using the token that was still "on file".

**Comment by fkooman** [comment]
The only way to recover from this currently, for the user, is to go the user portal and revoke the authorization, or remove all application data and restart the client.

**Comment by rozmansi** [comment]
Thank you for reporting this. The cause of this behaviour is my (now false) assumption that a profile gone missing is only temporary, thus the eduVPN client don't display it on the list.
Perhaps a simpler approach would be to completely forget the profile _and_ the access token alltogether, should the client detect the profile as missing.

François, your thoughts?

**Comment by fkooman** [comment]
See also #28 for the longer term idea on how to solve this. With the proposal in #28 this issue wouldn't have occurred.
